#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SMG_06

#include "Basic.hpp"

#include "ABP_SMG_06_classes.hpp"
#include "ABP_SMG_06_parameters.hpp"


namespace SDK
{

// Function ABP_SMG_06.ABP_SMG_06_C.ExecuteUbergraph_ABP_SMG_06
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_SMG_06_C::ExecuteUbergraph_ABP_SMG_06(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "ExecuteUbergraph_ABP_SMG_06");

	Params::ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_SMG_06.ABP_SMG_06_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_SMG_06_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "BlueprintUpdateAnimation");

	Params::ABP_SMG_06_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_SMG_06.ABP_SMG_06_C.CheckIfStanceChanged
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::CheckIfStanceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "CheckIfStanceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.RefreshPlayer
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::RefreshPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "RefreshPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.RefreshStance
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::RefreshStance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "RefreshStance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.CheckIfPlayerRefIsCorrect
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::CheckIfPlayerRefIsCorrect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "CheckIfPlayerRefIsCorrect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.SetStance
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::SetStance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "SetStance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.InitializeReferences
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::InitializeReferences()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "InitializeReferences");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_SMG_06_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UABP_SMG_06_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.AnimNotify_ReloadNotif
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::AnimNotify_ReloadNotif()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "AnimNotify_ReloadNotif");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.AnimNotify_SMG_06_Fired
// (BlueprintCallable, BlueprintEvent)

void UABP_SMG_06_C::AnimNotify_SMG_06_Fired()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "AnimNotify_SMG_06_Fired");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SMG_06_AnimGraphNode_ModifyBone_2C1EC80C4EF8B3A041AF4391A9694904
// (BlueprintEvent)

void UABP_SMG_06_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SMG_06_AnimGraphNode_ModifyBone_2C1EC80C4EF8B3A041AF4391A9694904()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SMG_06_AnimGraphNode_ModifyBone_2C1EC80C4EF8B3A041AF4391A9694904");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SMG_06.ABP_SMG_06_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_SMG_06_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SMG_06_C", "AnimGraph");

	Params::ABP_SMG_06_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

