#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SMG_06

#include "Basic.hpp"

#include "Flame_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function ABP_SMG_06.ABP_SMG_06_C.ExecuteUbergraph_ABP_SMG_06
// 0x00E8 (0x00E8 - 0x0000)
struct ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EStance                                       CallFunc_GetStance_ReturnValue;                    // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 CallFunc_GetOwningComponent_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue_1;                   // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Character_C*                        K2Node_DynamicCast_AsBP_Character;                 // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x003C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x004C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0060(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0068(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0070(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_2;        // 0x0088(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0094(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CallFunc_GetOwningComponent_ReturnValue_1;         // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue_2;                   // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue_3;                   // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Character_C*                        K2Node_DynamicCast_AsBP_Character_1;               // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x00DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x00DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x00DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x00DE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x00DF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06) == 0x000008, "Wrong alignment on ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06");
static_assert(sizeof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06) == 0x0000E8, "Wrong size on ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, EntryPoint) == 0x000000, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::EntryPoint' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetStance_ReturnValue) == 0x000005, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetStance_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetOwningComponent_ReturnValue) == 0x000008, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetOwningComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_1) == 0x000010, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetOwner_ReturnValue) == 0x000018, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_2) == 0x000020, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetOwner_ReturnValue_1) == 0x000028, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetOwner_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_DynamicCast_AsBP_Character) == 0x000030, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_DynamicCast_AsBP_Character' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_3) == 0x000039, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_CreateDelegate_OutputDelegate) == 0x00003C, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_CreateDelegate_OutputDelegate_1) == 0x00004C, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000060, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000068, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_CreateDelegate_OutputDelegate_2) == 0x000070, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, Temp_bool_Has_Been_Initd_Variable) == 0x000080, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_K2_SetTimerDelegate_ReturnValue_2) == 0x000088, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_K2_SetTimerDelegate_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000090, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_MakeRotator_ReturnValue) == 0x000094, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000A0, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, Temp_float_Variable) == 0x0000A4, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetOwningComponent_ReturnValue_1) == 0x0000A8, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetOwningComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_4) == 0x0000B0, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetOwner_ReturnValue_2) == 0x0000B8, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetOwner_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_5) == 0x0000C0, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_GetOwner_ReturnValue_3) == 0x0000C8, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_GetOwner_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_DynamicCast_AsBP_Character_1) == 0x0000D0, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_DynamicCast_AsBP_Character_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_DynamicCast_bSuccess_1) == 0x0000D8, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_6) == 0x0000D9, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, Temp_bool_IsClosed_Variable) == 0x0000DA, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_7) == 0x0000DB, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_IsValid_ReturnValue_8) == 0x0000DC, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0000DD, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, Temp_bool_Has_Been_Initd_Variable_1) == 0x0000DE, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, Temp_bool_IsClosed_Variable_1) == 0x0000DF, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06, K2Node_Event_DeltaTimeX) == 0x0000E0, "Member 'ABP_SMG_06_C_ExecuteUbergraph_ABP_SMG_06::K2Node_Event_DeltaTimeX' has a wrong offset!");

// Function ABP_SMG_06.ABP_SMG_06_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct ABP_SMG_06_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_SMG_06_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on ABP_SMG_06_C_BlueprintUpdateAnimation");
static_assert(sizeof(ABP_SMG_06_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on ABP_SMG_06_C_BlueprintUpdateAnimation");
static_assert(offsetof(ABP_SMG_06_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'ABP_SMG_06_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function ABP_SMG_06.ABP_SMG_06_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_SMG_06_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_SMG_06_C_AnimGraph) == 0x000008, "Wrong alignment on ABP_SMG_06_C_AnimGraph");
static_assert(sizeof(ABP_SMG_06_C_AnimGraph) == 0x000010, "Wrong size on ABP_SMG_06_C_AnimGraph");
static_assert(offsetof(ABP_SMG_06_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'ABP_SMG_06_C_AnimGraph::AnimGraph_0' has a wrong offset!");

}

