#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Armory_Tools

#include "Basic.hpp"

#include "BP_Armory_Tools_classes.hpp"
#include "BP_Armory_Tools_parameters.hpp"


namespace SDK
{

// Function BP_Armory_Tools.BP_Armory_Tools_C.ExecuteUbergraph_BP_Armory_Tools
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Armory_Tools_C::ExecuteUbergraph_BP_Armory_Tools(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "ExecuteUbergraph_BP_Armory_Tools");

	Params::BP_Armory_Tools_C_ExecuteUbergraph_BP_Armory_Tools Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.Clear
// (BlueprintCallable, BlueprintEvent)

void ABP_Armory_Tools_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Armory_Tools_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "ReceiveTick");

	Params::BP_Armory_Tools_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.Pre_Init
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Armory_C*                     ParentArmory_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Armory_Tools_C::Pre_Init(class ABP_Armory_C* ParentArmory_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "Pre_Init");

	Params::BP_Armory_Tools_C_Pre_Init Parms{};

	Parms.ParentArmory_0 = ParentArmory_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.Init
// (BlueprintCallable, BlueprintEvent)

void ABP_Armory_Tools_C::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.Update
// (BlueprintCallable, BlueprintEvent)

void ABP_Armory_Tools_C::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "Update");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.MakeDecalTransform
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform                       ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor)

struct FTransform ABP_Armory_Tools_C::MakeDecalTransform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "MakeDecalTransform");

	Params::BP_Armory_Tools_C_MakeDecalTransform Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Armory_Tools.BP_Armory_Tools_C.Gather All Sockets
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Armory_Tools_C::Gather_All_Sockets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Armory_Tools_C", "Gather All Sockets");

	UObject::ProcessEvent(Func, nullptr);
}

}

