#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AudioRepair

#include "Basic.hpp"

#include "BP_AudioRepair_classes.hpp"
#include "BP_AudioRepair_parameters.hpp"


namespace SDK
{

// Function BP_AudioRepair.BP_AudioRepair_C.ExecuteUbergraph_BP_AudioRepair
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioRepair_C::ExecuteUbergraph_BP_AudioRepair(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioRepair_C", "ExecuteUbergraph_BP_AudioRepair");

	Params::BP_AudioRepair_C_ExecuteUbergraph_BP_AudioRepair Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioRepair.BP_AudioRepair_C.LoadLevel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewLevel                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioRepair_C::LoadLevel(int32 NewLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioRepair_C", "LoadLevel");

	Params::BP_AudioRepair_C_LoadLevel Parms{};

	Parms.NewLevel = NewLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioRepair.BP_AudioRepair_C.FadeOutRoofs
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioRepair_C::FadeOutRoofs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioRepair_C", "FadeOutRoofs");

	UObject::ProcessEvent(Func, nullptr);
}

}

