#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArcadeMachine

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ArcadeMachine.BP_ArcadeMachine_C
// 0x0048 (0x0268 - 0x0220)
class ABP_ArcadeMachine_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class URectLightComponent*                    RectLight;                                         // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_InteractionItemComponent_C*         BP_InteractionItemComponent;                       // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         SizeX;                                             // 0x0250(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SizeY;                                             // 0x0254(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SearchingDepth;                                    // 0x0258(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Randomization;                                     // 0x025C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_PlayerState_C*                      Player_State;                                      // 0x0260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ArcadeMachine(int32 EntryPoint);
	void BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature(class UInteractionItemComponent* Sender, class AActor* Interacting_Actor);
	void SetArcadeGameOwnership(bool Owned);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ArcadeMachine_C">();
	}
	static class ABP_ArcadeMachine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ArcadeMachine_C>();
	}
};
static_assert(alignof(ABP_ArcadeMachine_C) == 0x000008, "Wrong alignment on ABP_ArcadeMachine_C");
static_assert(sizeof(ABP_ArcadeMachine_C) == 0x000268, "Wrong size on ABP_ArcadeMachine_C");
static_assert(offsetof(ABP_ArcadeMachine_C, UberGraphFrame) == 0x000220, "Member 'ABP_ArcadeMachine_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, RectLight) == 0x000228, "Member 'ABP_ArcadeMachine_C::RectLight' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, StaticMesh1) == 0x000230, "Member 'ABP_ArcadeMachine_C::StaticMesh1' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, StaticMesh) == 0x000238, "Member 'ABP_ArcadeMachine_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, BP_InteractionItemComponent) == 0x000240, "Member 'ABP_ArcadeMachine_C::BP_InteractionItemComponent' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, DefaultSceneRoot) == 0x000248, "Member 'ABP_ArcadeMachine_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, SizeX) == 0x000250, "Member 'ABP_ArcadeMachine_C::SizeX' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, SizeY) == 0x000254, "Member 'ABP_ArcadeMachine_C::SizeY' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, SearchingDepth) == 0x000258, "Member 'ABP_ArcadeMachine_C::SearchingDepth' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, Randomization) == 0x00025C, "Member 'ABP_ArcadeMachine_C::Randomization' has a wrong offset!");
static_assert(offsetof(ABP_ArcadeMachine_C, Player_State) == 0x000260, "Member 'ABP_ArcadeMachine_C::Player_State' has a wrong offset!");

}

