#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArcadeMachine

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ArcadeMachine.BP_ArcadeMachine_C.ExecuteUbergraph_BP_ArcadeMachine
// 0x0020 (0x0020 - 0x0000)
struct BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UInteractionItemComponent*              K2Node_ComponentBoundEvent_Sender;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_Interacting_Actor;      // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_TicTacToe_C*                        CallFunc_Create_ReturnValue;                       // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine) == 0x000008, "Wrong alignment on BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine");
static_assert(sizeof(BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine) == 0x000020, "Wrong size on BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine");
static_assert(offsetof(BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine, EntryPoint) == 0x000000, "Member 'BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine, K2Node_ComponentBoundEvent_Sender) == 0x000008, "Member 'BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine::K2Node_ComponentBoundEvent_Sender' has a wrong offset!");
static_assert(offsetof(BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine, K2Node_ComponentBoundEvent_Interacting_Actor) == 0x000010, "Member 'BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine::K2Node_ComponentBoundEvent_Interacting_Actor' has a wrong offset!");
static_assert(offsetof(BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine, CallFunc_Create_ReturnValue) == 0x000018, "Member 'BP_ArcadeMachine_C_ExecuteUbergraph_BP_ArcadeMachine::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function BP_ArcadeMachine.BP_ArcadeMachine_C.BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction Start On Client__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature final
{
public:
	class UInteractionItemComponent*              Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Interacting_Actor;                                 // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature) == 0x000008, "Wrong alignment on BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature");
static_assert(sizeof(BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature) == 0x000010, "Wrong size on BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature");
static_assert(offsetof(BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature, Sender) == 0x000000, "Member 'BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature::Sender' has a wrong offset!");
static_assert(offsetof(BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature, Interacting_Actor) == 0x000008, "Member 'BP_ArcadeMachine_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_1_Interaction_Start_On_Client__DelegateSignature::Interacting_Actor' has a wrong offset!");

// Function BP_ArcadeMachine.BP_ArcadeMachine_C.SetArcadeGameOwnership
// 0x0001 (0x0001 - 0x0000)
struct BP_ArcadeMachine_C_SetArcadeGameOwnership final
{
public:
	bool                                          Owned;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ArcadeMachine_C_SetArcadeGameOwnership) == 0x000001, "Wrong alignment on BP_ArcadeMachine_C_SetArcadeGameOwnership");
static_assert(sizeof(BP_ArcadeMachine_C_SetArcadeGameOwnership) == 0x000001, "Wrong size on BP_ArcadeMachine_C_SetArcadeGameOwnership");
static_assert(offsetof(BP_ArcadeMachine_C_SetArcadeGameOwnership, Owned) == 0x000000, "Member 'BP_ArcadeMachine_C_SetArcadeGameOwnership::Owned' has a wrong offset!");

}

