#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CandleLit_01

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CandleLit_01.BP_CandleLit_01_C
// 0x0020 (0x0240 - 0x0220)
class ABP_CandleLit_01_C final : public AActor
{
public:
	class UParticleSystemComponent*               PS_CandleFlame_01;                                 // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_candle_01;                                      // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Light_intensity;                                   // 0x0238(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CandleLit_01_C">();
	}
	static class ABP_CandleLit_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CandleLit_01_C>();
	}
};
static_assert(alignof(ABP_CandleLit_01_C) == 0x000008, "Wrong alignment on ABP_CandleLit_01_C");
static_assert(sizeof(ABP_CandleLit_01_C) == 0x000240, "Wrong size on ABP_CandleLit_01_C");
static_assert(offsetof(ABP_CandleLit_01_C, PS_CandleFlame_01) == 0x000220, "Member 'ABP_CandleLit_01_C::PS_CandleFlame_01' has a wrong offset!");
static_assert(offsetof(ABP_CandleLit_01_C, SM_candle_01) == 0x000228, "Member 'ABP_CandleLit_01_C::SM_candle_01' has a wrong offset!");
static_assert(offsetof(ABP_CandleLit_01_C, DefaultSceneRoot) == 0x000230, "Member 'ABP_CandleLit_01_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_CandleLit_01_C, Light_intensity) == 0x000238, "Member 'ABP_CandleLit_01_C::Light_intensity' has a wrong offset!");

}

