#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny

#include "Basic.hpp"

#include "Flame_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny.BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C.ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny
// 0x0128 (0x0128 - 0x0000)
struct BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress;    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(int32 PlayerId, float Damage, EDamageType DamageType, class UClass* DamagingItem)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Userid, float Damage, EDamageType DamageType)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x002C(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEventSystem*                           CallFunc_GetEventSystem_ReturnValue;               // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_GameState_GunFight_C*               K2Node_DynamicCast_AsBP_Game_State_Gun_Fight;      // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_EventSystem_C>    K2Node_DynamicCast_AsBPI_Event_System;             // 0x0068(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7A[0x6];                                       // 0x007A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EventSystem_C*                      CallFunc_Get_BP_event_system_Event_system;         // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress_1;  // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PlayerID;                       // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_Damage_1;                       // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDamageType                                   K2Node_CustomEvent_DamageType_1;                   // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9D[0x3];                                       // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_CustomEvent_DamagingItem;                   // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x3];                                       // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Round_ReturnValue;                        // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_UserId;                         // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_Damage;                         // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDamageType                                   K2Node_CustomEvent_DamageType;                     // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BA[0x2];                                       // 0x00BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress_2;  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Min_ReturnValue;                          // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEventSystem*                           CallFunc_GetEventSystem_ReturnValue_1;             // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 PlayerId, float Damage, EDamageType DamageType, class UClass* DamagingItem)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x00D0(0x0010)(ZeroConstructor, NoDestructor)
	TScriptInterface<class IBPI_EventSystem_C>    K2Node_DynamicCast_AsBPI_Event_System_1;           // 0x00E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(int32 Userid, float Damage, EDamageType DamageType)> K2Node_CreateDelegate_OutputDelegate_4;            // 0x00F4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EventSystem_C*                      CallFunc_Get_BP_event_system_Event_system_1;       // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0110(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny) == 0x000008, "Wrong alignment on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny");
static_assert(sizeof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny) == 0x000128, "Wrong size on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, EntryPoint) == 0x000000, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Get_Maximum_Progress_Maximum_Progress) == 0x000004, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Get_Maximum_Progress_Maximum_Progress' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, Temp_int_Variable) == 0x000028, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CreateDelegate_OutputDelegate_2) == 0x00002C, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Array_Length_ReturnValue) == 0x00003C, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Greater_IntInt_ReturnValue) == 0x000040, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Not_PreBool_ReturnValue) == 0x000041, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_GetGameState_ReturnValue) == 0x000048, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_GetEventSystem_ReturnValue) == 0x000050, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_GetEventSystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_DynamicCast_AsBP_Game_State_Gun_Fight) == 0x000058, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_DynamicCast_AsBP_Game_State_Gun_Fight' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_DynamicCast_bSuccess) == 0x000060, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_DynamicCast_AsBPI_Event_System) == 0x000068, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_DynamicCast_AsBPI_Event_System' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_DynamicCast_bSuccess_1) == 0x000078, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, Temp_bool_Variable) == 0x000079, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Get_BP_event_system_Event_system) == 0x000080, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Get_BP_event_system_Event_system' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_Select_Default) == 0x000088, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_IsValid_ReturnValue) == 0x00008C, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Get_Maximum_Progress_Maximum_Progress_1) == 0x000090, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Get_Maximum_Progress_Maximum_Progress_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_PlayerID) == 0x000094, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_PlayerID' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_Damage_1) == 0x000098, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_Damage_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_DamageType_1) == 0x00009C, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_DamageType_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_DamagingItem) == 0x0000A0, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_DamagingItem' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Less_IntInt_ReturnValue) == 0x0000A8, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Round_ReturnValue) == 0x0000AC, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_UserId) == 0x0000B0, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_UserId' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_Damage) == 0x0000B4, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_Damage' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CustomEvent_DamageType) == 0x0000B8, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CustomEvent_DamageType' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0000B9, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Add_IntInt_ReturnValue) == 0x0000BC, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Get_Maximum_Progress_Maximum_Progress_2) == 0x0000C0, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Get_Maximum_Progress_Maximum_Progress_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Min_ReturnValue) == 0x0000C4, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Min_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_GetEventSystem_ReturnValue_1) == 0x0000C8, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_GetEventSystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CreateDelegate_OutputDelegate_3) == 0x0000D0, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_DynamicCast_AsBPI_Event_System_1) == 0x0000E0, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_DynamicCast_AsBPI_Event_System_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_DynamicCast_bSuccess_2) == 0x0000F0, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CreateDelegate_OutputDelegate_4) == 0x0000F4, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_Get_BP_event_system_Event_system_1) == 0x000108, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_Get_BP_event_system_Event_system_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, K2Node_CreateDelegate_OutputDelegate_5) == 0x000110, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_IsValid_ReturnValue_1) == 0x000120, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000121, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_ExecuteUbergraph_BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");

// Function BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny.BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C.PlayerReceivedDamage
// 0x000C (0x000C - 0x0000)
struct BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage final
{
public:
	int32                                         Userid;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDamageType                                   DamageType;                                        // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage) == 0x000004, "Wrong alignment on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage");
static_assert(sizeof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage) == 0x00000C, "Wrong size on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage, Userid) == 0x000000, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage::Userid' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage, Damage) == 0x000004, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage::Damage' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage, DamageType) == 0x000008, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerReceivedDamage::DamageType' has a wrong offset!");

// Function BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny.BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C.PlayerDealtDamageEvent
// 0x0018 (0x0018 - 0x0000)
struct BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent final
{
public:
	int32                                         PlayerId;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDamageType                                   DamageType;                                        // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 DamagingItem;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent) == 0x000008, "Wrong alignment on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent");
static_assert(sizeof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent) == 0x000018, "Wrong size on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent, PlayerId) == 0x000000, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent::PlayerId' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent, Damage) == 0x000004, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent::Damage' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent, DamageType) == 0x000008, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent::DamageType' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent, DamagingItem) == 0x000010, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_PlayerDealtDamageEvent::DamagingItem' has a wrong offset!");

// Function BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny.BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C.Get Maximum Progress
// 0x0004 (0x0004 - 0x0000)
struct BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress final
{
public:
	int32                                         Maximum_Progress;                                  // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress) == 0x000004, "Wrong alignment on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress");
static_assert(sizeof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress) == 0x000004, "Wrong size on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress, Maximum_Progress) == 0x000000, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Maximum_Progress::Maximum_Progress' has a wrong offset!");

// Function BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny.BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C.Get Condition Text
// 0x0098 (0x0098 - 0x0000)
struct BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text final
{
public:
	class FText                                   Condition_Text;                                    // 0x0000(0x0018)(Parm, OutParm)
	class FText                                   CallFunc_Get_Condition_Text_Condition_Text;        // 0x0018(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0030(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0070(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0080(0x0018)()
};
static_assert(alignof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text) == 0x000008, "Wrong alignment on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text");
static_assert(sizeof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text) == 0x000098, "Wrong size on BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text, Condition_Text) == 0x000000, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text::Condition_Text' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text, CallFunc_Get_Condition_Text_Condition_Text) == 0x000018, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text::CallFunc_Get_Condition_Text_Condition_Text' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text, K2Node_MakeStruct_FormatArgumentData) == 0x000030, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text, K2Node_MakeArray_Array) == 0x000070, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text, CallFunc_Format_ReturnValue) == 0x000080, "Member 'BP_ChallengeCondition_GunfightDealDamageWithoutReceivingAny_C_Get_Condition_Text::CallFunc_Format_ReturnValue' has a wrong offset!");

}

