#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChallengeCondition_UseBoosterTickets

#include "Basic.hpp"

#include "Flame_structs.hpp"
#include "Engine_structs.hpp"
#include "EBooster_structs.hpp"


namespace SDK::Params
{

// Function BP_ChallengeCondition_UseBoosterTickets.BP_ChallengeCondition_UseBoosterTickets_C.ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets
// 0x0238 (0x0238 - 0x0000)
struct BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FChallengeParameter                    CallFunc_Array_Get_Item;                           // 0x0008(0x0010)(NoDestructor)
	struct FChallengeParameter                    CallFunc_Array_Get_Item_1;                         // 0x0018(0x0010)(NoDestructor)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Max_ReturnValue;                          // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress;    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x003E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F[0x1];                                       // 0x003F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UEventSystem*                           CallFunc_GetEventSystem_ReturnValue;               // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEventSystem*                           CallFunc_GetEventSystem_ReturnValue_1;             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_EventSystem_C*                      K2Node_DynamicCast_AsBP_Event_System;              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EventSystem_C*                      K2Node_DynamicCast_AsBP_Event_System_1;            // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress_1;  // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress_2;  // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class UClass*>            CallFunc_Get_Booster_Sku_Class_Info_SKU_To_Currency; // 0x0088(0x0050)()
	TMap<class UClass*, class FString>            CallFunc_Get_Booster_Sku_Class_Info_Currency_To_SKU; // 0x00D8(0x0050)()
	TMap<class UClass*, class FString>            CallFunc_Get_Booster_Sku_Class_Info_Currency_To_Gamemode; // 0x0128(0x0050)()
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_179[0x3];                                      // 0x0179(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBooster                                      K2Node_CustomEvent_Booster_Type;                   // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_UsedTicketInsteadOfCrowns;      // 0x0181(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_182[0x2];                                      // 0x0182(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetBoosterSkuFromEnum_ReturnValue;        // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A1[0x7];                                      // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_Map_Find_Value;                           // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B2[0x2];                                      // 0x01B2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EBooster Booster_Type, bool UsedTicketInsteadOfCrowns)> K2Node_CreateDelegate_OutputDelegate;              // 0x01B4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1C4[0x4];                                      // 0x01C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Map_Find_Value_1;                         // 0x01C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D9[0x7];                                      // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_GameState_C*                        K2Node_DynamicCast_AsBP_Game_State;                // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_StringIsEmpty_ReturnValue;                // 0x01F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F2[0x6];                                      // 0x01F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetGameModeStringName_StringName;         // 0x01F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Contains_ReturnValue;                     // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_209[0x3];                                      // 0x0209(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x020C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_21C[0x4];                                      // 0x021C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0220(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x022C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Min_ReturnValue;                          // 0x0230(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets) == 0x000008, "Wrong alignment on BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets");
static_assert(sizeof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets) == 0x000238, "Wrong size on BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, EntryPoint) == 0x000000, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_Get_Item) == 0x000008, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_Get_Item_1) == 0x000018, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_IsValidClass_ReturnValue) == 0x000028, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Max_ReturnValue) == 0x00002C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_Length_ReturnValue_1) == 0x000034, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Get_Maximum_Progress_Maximum_Progress) == 0x000038, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Get_Maximum_Progress_Maximum_Progress' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Greater_IntInt_ReturnValue) == 0x00003C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Less_IntInt_ReturnValue) == 0x00003D, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Not_PreBool_ReturnValue) == 0x00003E, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_GetEventSystem_ReturnValue) == 0x000040, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_GetEventSystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_GetEventSystem_ReturnValue_1) == 0x000048, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_GetEventSystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_DynamicCast_AsBP_Event_System) == 0x000050, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_DynamicCast_AsBP_Event_System' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_DynamicCast_AsBP_Event_System_1) == 0x000060, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_DynamicCast_AsBP_Event_System_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_DynamicCast_bSuccess_1) == 0x000068, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Get_Maximum_Progress_Maximum_Progress_1) == 0x00006C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Get_Maximum_Progress_Maximum_Progress_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000070, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Get_Maximum_Progress_Maximum_Progress_2) == 0x000074, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Get_Maximum_Progress_Maximum_Progress_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, Temp_int_Variable) == 0x000078, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_AddUnique_ReturnValue) == 0x00007C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, Temp_int_Loop_Counter_Variable) == 0x000080, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Get_Booster_Sku_Class_Info_SKU_To_Currency) == 0x000088, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Get_Booster_Sku_Class_Info_SKU_To_Currency' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Get_Booster_Sku_Class_Info_Currency_To_SKU) == 0x0000D8, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Get_Booster_Sku_Class_Info_Currency_To_SKU' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Get_Booster_Sku_Class_Info_Currency_To_Gamemode) == 0x000128, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Get_Booster_Sku_Class_Info_Currency_To_Gamemode' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Less_IntInt_ReturnValue_1) == 0x000178, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Add_IntInt_ReturnValue) == 0x00017C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_CustomEvent_Booster_Type) == 0x000180, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_CustomEvent_Booster_Type' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_CustomEvent_UsedTicketInsteadOfCrowns) == 0x000181, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_CustomEvent_UsedTicketInsteadOfCrowns' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_Length_ReturnValue_2) == 0x000184, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000188, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_GetBoosterSkuFromEnum_ReturnValue) == 0x000190, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_GetBoosterSkuFromEnum_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Not_PreBool_ReturnValue_1) == 0x0001A0, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Map_Find_Value) == 0x0001A8, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Map_Find_ReturnValue) == 0x0001B0, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Array_Contains_ReturnValue) == 0x0001B1, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_CreateDelegate_OutputDelegate) == 0x0001B4, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Map_Find_Value_1) == 0x0001C8, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Map_Find_ReturnValue_1) == 0x0001D8, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_GetGameState_ReturnValue) == 0x0001E0, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_DynamicCast_AsBP_Game_State) == 0x0001E8, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_DynamicCast_AsBP_Game_State' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_DynamicCast_bSuccess_2) == 0x0001F0, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_StringIsEmpty_ReturnValue) == 0x0001F1, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_StringIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_GetGameModeStringName_StringName) == 0x0001F8, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_GetGameModeStringName_StringName' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Contains_ReturnValue) == 0x000208, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, K2Node_CreateDelegate_OutputDelegate_1) == 0x00020C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000220, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Add_IntInt_ReturnValue_1) == 0x000228, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Add_IntInt_ReturnValue_2) == 0x00022C, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets, CallFunc_Min_ReturnValue) == 0x000230, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_ExecuteUbergraph_BP_ChallengeCondition_UseBoosterTickets::CallFunc_Min_ReturnValue' has a wrong offset!");

// Function BP_ChallengeCondition_UseBoosterTickets.BP_ChallengeCondition_UseBoosterTickets_C.BoosterTicketUsed
// 0x0002 (0x0002 - 0x0000)
struct BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed final
{
public:
	EBooster                                      Booster_Type;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UsedTicketInsteadOfCrowns;                         // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed) == 0x000001, "Wrong alignment on BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed");
static_assert(sizeof(BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed) == 0x000002, "Wrong size on BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed, Booster_Type) == 0x000000, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed::Booster_Type' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed, UsedTicketInsteadOfCrowns) == 0x000001, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_BoosterTicketUsed::UsedTicketInsteadOfCrowns' has a wrong offset!");

// Function BP_ChallengeCondition_UseBoosterTickets.BP_ChallengeCondition_UseBoosterTickets_C.Get Maximum Progress
// 0x0004 (0x0004 - 0x0000)
struct BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress final
{
public:
	int32                                         Maximum_Progress;                                  // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress) == 0x000004, "Wrong alignment on BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress");
static_assert(sizeof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress) == 0x000004, "Wrong size on BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress, Maximum_Progress) == 0x000000, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Maximum_Progress::Maximum_Progress' has a wrong offset!");

// Function BP_ChallengeCondition_UseBoosterTickets.BP_ChallengeCondition_UseBoosterTickets_C.Get Condition Text
// 0x00A0 (0x00A0 - 0x0000)
struct BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text final
{
public:
	class FText                                   Condition_Text;                                    // 0x0000(0x0018)(Parm, OutParm)
	int32                                         CallFunc_Get_Maximum_Progress_Maximum_Progress;    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Get_Condition_Text_Condition_Text;        // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text) == 0x000008, "Wrong alignment on BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text");
static_assert(sizeof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text) == 0x0000A0, "Wrong size on BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text, Condition_Text) == 0x000000, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text::Condition_Text' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text, CallFunc_Get_Maximum_Progress_Maximum_Progress) == 0x000018, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text::CallFunc_Get_Maximum_Progress_Maximum_Progress' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text, CallFunc_Get_Condition_Text_Condition_Text) == 0x000020, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text::CallFunc_Get_Condition_Text_Condition_Text' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text, K2Node_MakeArray_Array) == 0x000078, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text, CallFunc_Format_ReturnValue) == 0x000088, "Member 'BP_ChallengeCondition_UseBoosterTickets_C_Get_Condition_Text::CallFunc_Format_ReturnValue' has a wrong offset!");

}

