#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChallengeCondition_HeadshotWithWeapon

#include "Basic.hpp"

#include "Flame_structs.hpp"
#include "Engine_structs.hpp"
#include "E_ChallengeConditionEvaluationType_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "BP_ChallengeCondition_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ChallengeCondition_HeadshotWithWeapon.BP_ChallengeCondition_HeadshotWithWeapon_C
// 0x0090 (0x0410 - 0x0380)
class ABP_ChallengeCondition_HeadshotWithWeapon_C final : public ABP_ChallengeCondition_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ChallengeCondition_HeadshotWithWeapon_C; // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         Headshots_to_Score;                                // 0x0388(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38C[0x4];                                      // 0x038C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 Weapon_to_Use;                                     // 0x0390(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EItemCategory                                 Weapon_Category_to_Use;                            // 0x0398(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_399[0x7];                                      // 0x0399(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<EItemCategory>                           Valid_Item_Categories;                             // 0x03A0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	E_ChallengeConditionEvaluationType            Evaluation_Type;                                   // 0x03F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F1[0x7];                                      // 0x03F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Weapon_Name;                                       // 0x03F8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_ChallengeCondition_HeadshotWithWeapon(int32 EntryPoint);
	void Player_Scored_Kill(class AHumanCharacter* Killer, class AHumanCharacter* Victim, float Damage_Amount, EDamageType Damage_Type, class UClass* Instigating_Item, const struct FHitResult& Hit_Result);
	void ReceiveBeginPlay();
	void Get_Maximum_Progress(int32* Maximum_Progress);
	void Get_Condition_Text(class FText* Condition_Text);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ChallengeCondition_HeadshotWithWeapon_C">();
	}
	static class ABP_ChallengeCondition_HeadshotWithWeapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ChallengeCondition_HeadshotWithWeapon_C>();
	}
};
static_assert(alignof(ABP_ChallengeCondition_HeadshotWithWeapon_C) == 0x000008, "Wrong alignment on ABP_ChallengeCondition_HeadshotWithWeapon_C");
static_assert(sizeof(ABP_ChallengeCondition_HeadshotWithWeapon_C) == 0x000410, "Wrong size on ABP_ChallengeCondition_HeadshotWithWeapon_C");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, UberGraphFrame_BP_ChallengeCondition_HeadshotWithWeapon_C) == 0x000380, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::UberGraphFrame_BP_ChallengeCondition_HeadshotWithWeapon_C' has a wrong offset!");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, Headshots_to_Score) == 0x000388, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::Headshots_to_Score' has a wrong offset!");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, Weapon_to_Use) == 0x000390, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::Weapon_to_Use' has a wrong offset!");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, Weapon_Category_to_Use) == 0x000398, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::Weapon_Category_to_Use' has a wrong offset!");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, Valid_Item_Categories) == 0x0003A0, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::Valid_Item_Categories' has a wrong offset!");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, Evaluation_Type) == 0x0003F0, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::Evaluation_Type' has a wrong offset!");
static_assert(offsetof(ABP_ChallengeCondition_HeadshotWithWeapon_C, Weapon_Name) == 0x0003F8, "Member 'ABP_ChallengeCondition_HeadshotWithWeapon_C::Weapon_Name' has a wrong offset!");

}

