#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Interactable_WorldMap

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Interactable_WorldMap.BP_Interactable_WorldMap_C.ExecuteUbergraph_BP_Interactable_WorldMap
// 0x0080 (0x0080 - 0x0000)
struct BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class ABP_GameMode_Shelter_C*                 K2Node_DynamicCast_AsBP_Game_Mode_Shelter;         // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue_1;                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_GameMode_Shelter_C*                 K2Node_DynamicCast_AsBP_Game_Mode_Shelter_1;       // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UInteractionItemComponent*              K2Node_ComponentBoundEvent_Sender;                 // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_Interacting_Actor;      // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACharacter*                             K2Node_DynamicCast_AsCharacter;                    // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller;            // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap) == 0x000008, "Wrong alignment on BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap");
static_assert(sizeof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap) == 0x000080, "Wrong size on BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, EntryPoint) == 0x000000, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, CallFunc_GetGameMode_ReturnValue) == 0x000008, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_AsBP_Game_Mode_Shelter) == 0x000020, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_AsBP_Game_Mode_Shelter' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, CallFunc_IsValid_ReturnValue) == 0x000029, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, CallFunc_GetGameMode_ReturnValue_1) == 0x000030, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::CallFunc_GetGameMode_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_AsBP_Game_Mode_Shelter_1) == 0x000038, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_AsBP_Game_Mode_Shelter_1' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_bSuccess_1) == 0x000040, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, CallFunc_IsValid_ReturnValue_1) == 0x000041, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_ComponentBoundEvent_Sender) == 0x000048, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_ComponentBoundEvent_Sender' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_ComponentBoundEvent_Interacting_Actor) == 0x000050, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_ComponentBoundEvent_Interacting_Actor' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_AsCharacter) == 0x000058, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_AsCharacter' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_bSuccess_2) == 0x000060, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, CallFunc_GetController_ReturnValue) == 0x000068, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_AsPlayer_Controller) == 0x000070, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_AsPlayer_Controller' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap, K2Node_DynamicCast_bSuccess_3) == 0x000078, "Member 'BP_Interactable_WorldMap_C_ExecuteUbergraph_BP_Interactable_WorldMap::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");

// Function BP_Interactable_WorldMap.BP_Interactable_WorldMap_C.BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction Start On Client__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature final
{
public:
	class UInteractionItemComponent*              Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Interacting_Actor;                                 // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature) == 0x000008, "Wrong alignment on BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature");
static_assert(sizeof(BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature) == 0x000010, "Wrong size on BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature");
static_assert(offsetof(BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature, Sender) == 0x000000, "Member 'BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature::Sender' has a wrong offset!");
static_assert(offsetof(BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature, Interacting_Actor) == 0x000008, "Member 'BP_Interactable_WorldMap_C_BndEvt__BP_InteractionItemComponent_K2Node_ComponentBoundEvent_0_Interaction_Start_On_Client__DelegateSignature::Interacting_Actor' has a wrong offset!");

}

