#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MementoShelterObject

#include "Basic.hpp"

#include "Flame_structs.hpp"


namespace SDK::Params
{

// Function BP_MementoShelterObject.BP_MementoShelterObject_C.ExecuteUbergraph_BP_MementoShelterObject
// 0x0088 (0x0088 - 0x0000)
struct BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataTable*                             CallFunc_DataProviderFindTableByAssetTable_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AStash*                                 CallFunc_GetStash_ReturnValue;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23[0x1];                                       // 0x0023(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetUserControllerId_ReturnValue;          // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHumanPlayerController*                 CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EGameScenario                                 CallFunc_GetGameScenario_ReturnValue;              // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class AStash* Sender, class UStashComponent* Inventory)> K2Node_CreateDelegate_OutputDelegate;              // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetUserControllerId_ReturnValue_1;        // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHumanPlayerController*                 CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue_1; // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AStash*                                 K2Node_CustomEvent_Sender;                         // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStashComponent*                        K2Node_CustomEvent_Inventory;                      // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerState_C*                      K2Node_DynamicCast_AsBP_Player_State;              // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_72[0x6];                                       // 0x0072(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AStash*                                 CallFunc_GetStash_ReturnValue_1;                   // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_CountOfResource_ReturnValue;              // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0085(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0086(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject) == 0x000008, "Wrong alignment on BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject");
static_assert(sizeof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject) == 0x000088, "Wrong size on BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, EntryPoint) == 0x000000, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_DataProviderFindTableByAssetTable_ReturnValue) == 0x000008, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_DataProviderFindTableByAssetTable_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetStash_ReturnValue) == 0x000018, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetStash_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue_1) == 0x000020, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue_2) == 0x000021, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue_3) == 0x000022, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetUserControllerId_ReturnValue) == 0x000024, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetUserControllerId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue) == 0x000028, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue_4) == 0x000030, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetGameScenario_ReturnValue) == 0x000031, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetGameScenario_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, K2Node_CreateDelegate_OutputDelegate) == 0x000034, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetUserControllerId_ReturnValue_1) == 0x000044, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetUserControllerId_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue_1) == 0x000048, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, K2Node_CustomEvent_Sender) == 0x000050, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::K2Node_CustomEvent_Sender' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, K2Node_CustomEvent_Inventory) == 0x000058, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::K2Node_CustomEvent_Inventory' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_MakeLiteralByte_ReturnValue) == 0x000060, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, K2Node_DynamicCast_AsBP_Player_State) == 0x000068, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::K2Node_DynamicCast_AsBP_Player_State' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000071, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_GetStash_ReturnValue_1) == 0x000078, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_GetStash_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_CountOfResource_ReturnValue) == 0x000080, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_CountOfResource_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue_5) == 0x000084, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_Greater_IntInt_ReturnValue) == 0x000085, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject, CallFunc_IsValid_ReturnValue_6) == 0x000086, "Member 'BP_MementoShelterObject_C_ExecuteUbergraph_BP_MementoShelterObject::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");

// Function BP_MementoShelterObject.BP_MementoShelterObject_C.Stash Loaded
// 0x0010 (0x0010 - 0x0000)
struct BP_MementoShelterObject_C_Stash_Loaded final
{
public:
	class AStash*                                 Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStashComponent*                        Inventory;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MementoShelterObject_C_Stash_Loaded) == 0x000008, "Wrong alignment on BP_MementoShelterObject_C_Stash_Loaded");
static_assert(sizeof(BP_MementoShelterObject_C_Stash_Loaded) == 0x000010, "Wrong size on BP_MementoShelterObject_C_Stash_Loaded");
static_assert(offsetof(BP_MementoShelterObject_C_Stash_Loaded, Sender) == 0x000000, "Member 'BP_MementoShelterObject_C_Stash_Loaded::Sender' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Stash_Loaded, Inventory) == 0x000008, "Member 'BP_MementoShelterObject_C_Stash_Loaded::Inventory' has a wrong offset!");

// Function BP_MementoShelterObject.BP_MementoShelterObject_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct BP_MementoShelterObject_C_UserConstructionScript final
{
public:
	class UDataTable*                             CallFunc_DataProviderFindTableByAssetTable_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MementoShelterObject_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_MementoShelterObject_C_UserConstructionScript");
static_assert(sizeof(BP_MementoShelterObject_C_UserConstructionScript) == 0x000008, "Wrong size on BP_MementoShelterObject_C_UserConstructionScript");
static_assert(offsetof(BP_MementoShelterObject_C_UserConstructionScript, CallFunc_DataProviderFindTableByAssetTable_ReturnValue) == 0x000000, "Member 'BP_MementoShelterObject_C_UserConstructionScript::CallFunc_DataProviderFindTableByAssetTable_ReturnValue' has a wrong offset!");

// Function BP_MementoShelterObject.BP_MementoShelterObject_C.Set Visuals
// 0x0370 (0x0370 - 0x0000)
struct BP_MementoShelterObject_C_Set_Visuals final
{
public:
	class UDataTable*                             Data_Table;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCollectiblesList                      Table_Row;                                         // 0x0008(0x0150)(Edit, BlueprintVisible)
	int32                                         Temp_int_Variable;                                 // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_169[0x3];                                      // 0x0169(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CallFunc_GetDataTableRowNames_OutRowNames;         // 0x0178(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x3];                                      // 0x0189(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Array_Get_Item;                           // 0x018C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_194[0x4];                                      // 0x0194(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCollectiblesList                      CallFunc_GetDataTableRowFromName_OutRow;           // 0x0198(0x0150)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E9[0x3];                                      // 0x02E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x02EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F2[0x2];                                      // 0x02F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetNumMaterials_ReturnValue;              // 0x02F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_LoadSoftReference_ReturnValue;            // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0304(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0305(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_306[0x2];                                      // 0x0306(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            K2Node_DynamicCast_AsStatic_Mesh;                  // 0x0308(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x0311(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0312(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_313[0x5];                                      // 0x0313(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UMaterialInstance>       CallFunc_Array_Get_Item_1;                         // 0x0318(0x0028)(HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0340(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_341[0x7];                                      // 0x0341(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_LoadSoftReference_ReturnValue_1;          // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x7];                                      // 0x0351(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     K2Node_DynamicCast_AsMaterial_Interface;           // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue_1; // 0x0361(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_362[0x2];                                      // 0x0362(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0364(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0368(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0369(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x036A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_MementoShelterObject_C_Set_Visuals) == 0x000008, "Wrong alignment on BP_MementoShelterObject_C_Set_Visuals");
static_assert(sizeof(BP_MementoShelterObject_C_Set_Visuals) == 0x000370, "Wrong size on BP_MementoShelterObject_C_Set_Visuals");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, Data_Table) == 0x000000, "Member 'BP_MementoShelterObject_C_Set_Visuals::Data_Table' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, Table_Row) == 0x000008, "Member 'BP_MementoShelterObject_C_Set_Visuals::Table_Row' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, Temp_int_Variable) == 0x000158, "Member 'BP_MementoShelterObject_C_Set_Visuals::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Add_IntInt_ReturnValue) == 0x00015C, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, Temp_int_Loop_Counter_Variable) == 0x000160, "Member 'BP_MementoShelterObject_C_Set_Visuals::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Add_IntInt_ReturnValue_1) == 0x000164, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, Temp_bool_True_if_break_was_hit_Variable) == 0x000168, "Member 'BP_MementoShelterObject_C_Set_Visuals::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, Temp_int_Array_Index_Variable) == 0x00016C, "Member 'BP_MementoShelterObject_C_Set_Visuals::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Not_PreBool_ReturnValue) == 0x000170, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_GetDataTableRowNames_OutRowNames) == 0x000178, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_GetDataTableRowNames_OutRowNames' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_IsValidClass_ReturnValue) == 0x000188, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Array_Get_Item) == 0x00018C, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_GetDataTableRowFromName_OutRow) == 0x000198, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x0002E8, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Array_Length_ReturnValue) == 0x0002EC, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Less_IntInt_ReturnValue) == 0x0002F0, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_BooleanAND_ReturnValue) == 0x0002F1, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_GetNumMaterials_ReturnValue) == 0x0002F4, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_GetNumMaterials_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_LoadSoftReference_ReturnValue) == 0x0002F8, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_LoadSoftReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Subtract_IntInt_ReturnValue) == 0x000300, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_IsValid_ReturnValue) == 0x000304, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000305, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, K2Node_DynamicCast_AsStatic_Mesh) == 0x000308, "Member 'BP_MementoShelterObject_C_Set_Visuals::K2Node_DynamicCast_AsStatic_Mesh' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, K2Node_DynamicCast_bSuccess) == 0x000310, "Member 'BP_MementoShelterObject_C_Set_Visuals::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x000311, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_SetStaticMesh_ReturnValue) == 0x000312, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Array_Get_Item_1) == 0x000318, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000340, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_LoadSoftReference_ReturnValue_1) == 0x000348, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_LoadSoftReference_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_IsValid_ReturnValue_1) == 0x000350, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, K2Node_DynamicCast_AsMaterial_Interface) == 0x000358, "Member 'BP_MementoShelterObject_C_Set_Visuals::K2Node_DynamicCast_AsMaterial_Interface' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, K2Node_DynamicCast_bSuccess_1) == 0x000360, "Member 'BP_MementoShelterObject_C_Set_Visuals::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_IsValidSoftObjectReference_ReturnValue_1) == 0x000361, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_IsValidSoftObjectReference_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Array_Length_ReturnValue_1) == 0x000364, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Greater_IntInt_ReturnValue) == 0x000368, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_Not_PreBool_ReturnValue_1) == 0x000369, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MementoShelterObject_C_Set_Visuals, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x00036A, "Member 'BP_MementoShelterObject_C_Set_Visuals::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");

}

