#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_ProSplineActor

#include "Basic.hpp"

#include "bp_ProSplineActor_classes.hpp"
#include "bp_ProSplineActor_parameters.hpp"


namespace SDK
{

// Function bp_ProSplineActor.bp_ProSplineActor_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Abp_ProSplineActor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("bp_ProSplineActor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

