#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShelterWardrobeCamera

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.ExecuteUbergraph_BP_ShelterWardrobeCamera
// 0x00B0 (0x00B0 - 0x0000)
struct BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_RInterpTo_ReturnValue;                    // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x0010(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_EqualEqual_VectorVector_ReturnValue;      // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_RotatorRotator_ReturnValue;    // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x009E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9F[0x1];                                       // 0x009F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VInterpTo_ReturnValue;                    // 0x00A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera) == 0x000004, "Wrong alignment on BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera) == 0x0000B0, "Wrong size on BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, EntryPoint) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, CallFunc_RInterpTo_ReturnValue) == 0x000004, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::CallFunc_RInterpTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x000010, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, CallFunc_EqualEqual_VectorVector_ReturnValue) == 0x00009C, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::CallFunc_EqualEqual_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, CallFunc_EqualEqual_RotatorRotator_ReturnValue) == 0x00009D, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::CallFunc_EqualEqual_RotatorRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, CallFunc_BooleanAND_ReturnValue) == 0x00009E, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, K2Node_Event_DeltaSeconds) == 0x0000A0, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera, CallFunc_VInterpTo_ReturnValue) == 0x0000A4, "Member 'BP_ShelterWardrobeCamera_C_ExecuteUbergraph_BP_ShelterWardrobeCamera::CallFunc_VInterpTo_ReturnValue' has a wrong offset!");

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_ShelterWardrobeCamera_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_ShelterWardrobeCamera_C_ReceiveTick");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_ReceiveTick) == 0x000004, "Wrong size on BP_ShelterWardrobeCamera_C_ReceiveTick");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.UseWardrobePreviewCamera
// 0x0178 (0x0178 - 0x0000)
struct BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera final
{
public:
	class ABP_PlayerController_Shelter_C*         PlayerControllerShelter;                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 PreviousViewTarget_0;                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInstantTransition;                                // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0014(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetCameraRotation_ReturnValue;            // 0x0038(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetCameraLocation_ReturnValue;            // 0x0044(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue_1;    // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x005C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult_1; // 0x00E8(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera) == 0x000008, "Wrong alignment on BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera) == 0x000178, "Wrong size on BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, PlayerControllerShelter) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::PlayerControllerShelter' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, PreviousViewTarget_0) == 0x000008, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::PreviousViewTarget_0' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, bInstantTransition) == 0x000010, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::bInstantTransition' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000014, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000020, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x00002C, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_GetCameraRotation_ReturnValue) == 0x000038, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_GetCameraRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_GetCameraLocation_ReturnValue) == 0x000044, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_GetCameraLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_K2_GetComponentRotation_ReturnValue_1) == 0x000050, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_K2_GetComponentRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x00005C, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult_1) == 0x0000E8, "Member 'BP_ShelterWardrobeCamera_C_UseWardrobePreviewCamera::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult_1' has a wrong offset!");

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.DeactivateAllCameras
// 0x0001 (0x0001 - 0x0000)
struct BP_ShelterWardrobeCamera_C_DeactivateAllCameras final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_DeactivateAllCameras) == 0x000001, "Wrong alignment on BP_ShelterWardrobeCamera_C_DeactivateAllCameras");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_DeactivateAllCameras) == 0x000001, "Wrong size on BP_ShelterWardrobeCamera_C_DeactivateAllCameras");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_DeactivateAllCameras, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_DeactivateAllCameras::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.StopUsingWardrobePreviewCamera
// 0x0170 (0x0170 - 0x0000)
struct BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera final
{
public:
	bool                                          bInstantTransition;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 PreviousViewTarget_0;                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_PlayerController_Shelter_C*         PlayerController_0;                                // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Character_Script_C*                 K2Node_DynamicCast_AsBP_Character_Script;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0024(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x003C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue_1;    // 0x00C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x00D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult_1; // 0x00E0(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera) == 0x000008, "Wrong alignment on BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera) == 0x000170, "Wrong size on BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, bInstantTransition) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::bInstantTransition' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, PreviousViewTarget_0) == 0x000008, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::PreviousViewTarget_0' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, PlayerController_0) == 0x000010, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::PlayerController_0' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, K2Node_DynamicCast_AsBP_Character_Script) == 0x000018, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::K2Node_DynamicCast_AsBP_Character_Script' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000024, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000030, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x00003C, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, CallFunc_K2_GetComponentRotation_ReturnValue_1) == 0x0000C8, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::CallFunc_K2_GetComponentRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x0000D4, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult_1) == 0x0000E0, "Member 'BP_ShelterWardrobeCamera_C_StopUsingWardrobePreviewCamera::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult_1' has a wrong offset!");

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.PreviewPoster
// 0x00F0 (0x00F0 - 0x0000)
struct BP_ShelterWardrobeCamera_C_PreviewPoster final
{
public:
	struct FTransform                             PosterCameraTransform;                             // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	class ABP_PlayerController_Shelter_C*         PlayerController_0;                                // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 PrevViewTarget;                                    // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0040(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x0064(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_PreviewPoster) == 0x000010, "Wrong alignment on BP_ShelterWardrobeCamera_C_PreviewPoster");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_PreviewPoster) == 0x0000F0, "Wrong size on BP_ShelterWardrobeCamera_C_PreviewPoster");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, PosterCameraTransform) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::PosterCameraTransform' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, PlayerController_0) == 0x000030, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::PlayerController_0' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, PrevViewTarget) == 0x000038, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::PrevViewTarget' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, CallFunc_BreakTransform_Location) == 0x000040, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, CallFunc_BreakTransform_Rotation) == 0x00004C, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, CallFunc_BreakTransform_Scale) == 0x000058, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_PreviewPoster, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x000064, "Member 'BP_ShelterWardrobeCamera_C_PreviewPoster::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");

// Function BP_ShelterWardrobeCamera.BP_ShelterWardrobeCamera_C.SetViewTarget
// 0x0018 (0x0018 - 0x0000)
struct BP_ShelterWardrobeCamera_C_SetViewTarget final
{
public:
	class ABP_PlayerController_Shelter_C*         PlayerController_0;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 NewViewTarget;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bUseTheCamera;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bPosterCamera;                                     // 0x0011(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ShelterWardrobeCamera_C_SetViewTarget) == 0x000008, "Wrong alignment on BP_ShelterWardrobeCamera_C_SetViewTarget");
static_assert(sizeof(BP_ShelterWardrobeCamera_C_SetViewTarget) == 0x000018, "Wrong size on BP_ShelterWardrobeCamera_C_SetViewTarget");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_SetViewTarget, PlayerController_0) == 0x000000, "Member 'BP_ShelterWardrobeCamera_C_SetViewTarget::PlayerController_0' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_SetViewTarget, NewViewTarget) == 0x000008, "Member 'BP_ShelterWardrobeCamera_C_SetViewTarget::NewViewTarget' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_SetViewTarget, bUseTheCamera) == 0x000010, "Member 'BP_ShelterWardrobeCamera_C_SetViewTarget::bUseTheCamera' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_SetViewTarget, bPosterCamera) == 0x000011, "Member 'BP_ShelterWardrobeCamera_C_SetViewTarget::bPosterCamera' has a wrong offset!");
static_assert(offsetof(BP_ShelterWardrobeCamera_C_SetViewTarget, CallFunc_IsValid_ReturnValue) == 0x000012, "Member 'BP_ShelterWardrobeCamera_C_SetViewTarget::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

