#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TitleLogic_ShelterImprovementsBuilt

#include "Basic.hpp"

#include "F_TitleRank_structs.hpp"


namespace SDK::Params
{

// Function BP_TitleLogic_ShelterImprovementsBuilt.BP_TitleLogic_ShelterImprovementsBuilt_C.ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt
// 0x0040 (0x0040 - 0x0000)
struct BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetUserControllerId_ReturnValue;          // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHumanPlayerController*                 CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_PlayerState_C*                      K2Node_DynamicCast_AsBP_Player_State;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AStash*                                 CallFunc_GetStash_ReturnValue;                     // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt) == 0x000008, "Wrong alignment on BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt");
static_assert(sizeof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt) == 0x000040, "Wrong size on BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, EntryPoint) == 0x000000, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, CallFunc_GetUserControllerId_ReturnValue) == 0x000014, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::CallFunc_GetUserControllerId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue) == 0x000018, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::CallFunc_GetHumanPlayerControllerByControllerId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, K2Node_DynamicCast_AsBP_Player_State) == 0x000020, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::K2Node_DynamicCast_AsBP_Player_State' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, CallFunc_GetStash_ReturnValue) == 0x000030, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::CallFunc_GetStash_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt, CallFunc_IsValid_ReturnValue) == 0x000038, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_ExecuteUbergraph_BP_TitleLogic_ShelterImprovementsBuilt::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_TitleLogic_ShelterImprovementsBuilt.BP_TitleLogic_ShelterImprovementsBuilt_C.Is Initialized
// 0x0001 (0x0001 - 0x0000)
struct BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized final
{
public:
	bool                                          Initialized;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized) == 0x000001, "Wrong alignment on BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized");
static_assert(sizeof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized) == 0x000001, "Wrong size on BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized, Initialized) == 0x000000, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Initialized::Initialized' has a wrong offset!");

// Function BP_TitleLogic_ShelterImprovementsBuilt.BP_TitleLogic_ShelterImprovementsBuilt_C.Is Rank Owned
// 0x00D0 (0x00D0 - 0x0000)
struct BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned final
{
public:
	struct FF_TitleRank                           Rank_Info;                                         // 0x0000(0x00B8)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          Owned;                                             // 0x00B8(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AStash*                                 CallFunc_GetStash_ReturnValue;                     // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetImprovementsCount_ReturnValue;         // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned) == 0x000008, "Wrong alignment on BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned");
static_assert(sizeof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned) == 0x0000D0, "Wrong size on BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned, Rank_Info) == 0x000000, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned::Rank_Info' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned, Owned) == 0x0000B8, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned::Owned' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned, CallFunc_GetStash_ReturnValue) == 0x0000C0, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned::CallFunc_GetStash_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned, CallFunc_GetImprovementsCount_ReturnValue) == 0x0000C8, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned::CallFunc_GetImprovementsCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x0000CC, "Member 'BP_TitleLogic_ShelterImprovementsBuilt_C_Is_Rank_Owned::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");

}

