#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ToolArmoryDecal

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ToolArmoryDecal.BP_ToolArmoryDecal_C.ExecuteUbergraph_BP_ToolArmoryDecal
// 0x0004 (0x0004 - 0x0000)
struct BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal) == 0x000004, "Wrong alignment on BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal");
static_assert(sizeof(BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal) == 0x000004, "Wrong size on BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal");
static_assert(offsetof(BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal, EntryPoint) == 0x000000, "Member 'BP_ToolArmoryDecal_C_ExecuteUbergraph_BP_ToolArmoryDecal::EntryPoint' has a wrong offset!");

}

