#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_Armory_WeaponElement

#include "Basic.hpp"

#include "S_Armory_WeaponData_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_Armory_WeaponElement.BPC_Armory_WeaponElement_C
// 0x0138 (0x01E8 - 0x00B0)
class UBPC_Armory_WeaponElement_C final : public UActorComponent
{
public:
	class UStaticMeshComponent*                   BlueprintMesh_Component;                           // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_ArmoryDecal_C*                      Decal_ChildActor;                                  // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Weapon_C;                                          // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Rack_Index;                                        // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   WeaponSocket;                                      // 0x00CC(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_Armory_WeaponData                   WeaponData;                                        // 0x00D8(0x00F0)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UStaticMeshComponent*                   WeaponMesh_Component_SM;                           // 0x01C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 ExtraSkinMesh;                                     // 0x01D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 WeaponMesh_Component_SK;                           // 0x01D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UsedStaticMesh;                                    // 0x01E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void GetWeaponMesh(class UMeshComponent** Mesh) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_Armory_WeaponElement_C">();
	}
	static class UBPC_Armory_WeaponElement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_Armory_WeaponElement_C>();
	}
};
static_assert(alignof(UBPC_Armory_WeaponElement_C) == 0x000008, "Wrong alignment on UBPC_Armory_WeaponElement_C");
static_assert(sizeof(UBPC_Armory_WeaponElement_C) == 0x0001E8, "Wrong size on UBPC_Armory_WeaponElement_C");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, BlueprintMesh_Component) == 0x0000B0, "Member 'UBPC_Armory_WeaponElement_C::BlueprintMesh_Component' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, Decal_ChildActor) == 0x0000B8, "Member 'UBPC_Armory_WeaponElement_C::Decal_ChildActor' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, Weapon_C) == 0x0000C0, "Member 'UBPC_Armory_WeaponElement_C::Weapon_C' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, Rack_Index) == 0x0000C8, "Member 'UBPC_Armory_WeaponElement_C::Rack_Index' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, WeaponSocket) == 0x0000CC, "Member 'UBPC_Armory_WeaponElement_C::WeaponSocket' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, WeaponData) == 0x0000D8, "Member 'UBPC_Armory_WeaponElement_C::WeaponData' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, WeaponMesh_Component_SM) == 0x0001C8, "Member 'UBPC_Armory_WeaponElement_C::WeaponMesh_Component_SM' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, ExtraSkinMesh) == 0x0001D0, "Member 'UBPC_Armory_WeaponElement_C::ExtraSkinMesh' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, WeaponMesh_Component_SK) == 0x0001D8, "Member 'UBPC_Armory_WeaponElement_C::WeaponMesh_Component_SK' has a wrong offset!");
static_assert(offsetof(UBPC_Armory_WeaponElement_C, UsedStaticMesh) == 0x0001E0, "Member 'UBPC_Armory_WeaponElement_C::UsedStaticMesh' has a wrong offset!");

}

