#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayersShelter_02

#include "Basic.hpp"


namespace SDK::Params
{

// Function PlayersShelter_02.PlayersShelter_02_C.ExecuteUbergraph_PlayersShelter_02
// 0x0004 (0x0004 - 0x0000)
struct PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02) == 0x000004, "Wrong alignment on PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02");
static_assert(sizeof(PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02) == 0x000004, "Wrong size on PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02");
static_assert(offsetof(PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02, EntryPoint) == 0x000000, "Member 'PlayersShelter_02_C_ExecuteUbergraph_PlayersShelter_02::EntryPoint' has a wrong offset!");

}

