#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CharityBox_Notification

#include "Basic.hpp"

#include "UI_CharityBox_Notification_classes.hpp"
#include "UI_CharityBox_Notification_parameters.hpp"


namespace SDK
{

// Function UI_CharityBox_Notification.UI_CharityBox_Notification_C.ExecuteUbergraph_UI_CharityBox_Notification
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharityBox_Notification_C::ExecuteUbergraph_UI_CharityBox_Notification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharityBox_Notification_C", "ExecuteUbergraph_UI_CharityBox_Notification");

	Params::UI_CharityBox_Notification_C_ExecuteUbergraph_UI_CharityBox_Notification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharityBox_Notification.UI_CharityBox_Notification_C.OnShow
// (Event, Public, BlueprintEvent)

void UUI_CharityBox_Notification_C::OnShow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharityBox_Notification_C", "OnShow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharityBox_Notification.UI_CharityBox_Notification_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_CharityBox_Notification_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharityBox_Notification_C", "PreConstruct");

	Params::UI_CharityBox_Notification_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharityBox_Notification.UI_CharityBox_Notification_C.OnHide
// (Event, Public, BlueprintEvent)

void UUI_CharityBox_Notification_C::OnHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharityBox_Notification_C", "OnHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharityBox_Notification.UI_CharityBox_Notification_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_CharityBox_Notification_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharityBox_Notification_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharityBox_Notification.UI_CharityBox_Notification_C.CountMilestones
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FCloudCharityBoxSeasonMilestoneInfo>MilestoneInfo_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   DonatedFood_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   FulfilledMilestones                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharityBox_Notification_C::CountMilestones(TArray<struct FCloudCharityBoxSeasonMilestoneInfo>& MilestoneInfo_0, int32 DonatedFood_0, int32* FulfilledMilestones)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharityBox_Notification_C", "CountMilestones");

	Params::UI_CharityBox_Notification_C_CountMilestones Parms{};

	Parms.MilestoneInfo_0 = std::move(MilestoneInfo_0);
	Parms.DonatedFood_0 = DonatedFood_0;

	UObject::ProcessEvent(Func, &Parms);

	MilestoneInfo_0 = std::move(Parms.MilestoneInfo_0);

	if (FulfilledMilestones != nullptr)
		*FulfilledMilestones = Parms.FulfilledMilestones;
}

}

