#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CharityBox_Rewards

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_CharityBox_Rewards.UI_CharityBox_Rewards_C
// 0x0080 (0x0358 - 0x02D8)
class UUI_CharityBox_Rewards_C final : public UMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFlameTextBlock*                        FlameTextBlock_227;                                // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        FlameTextBlock_Category;                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        FlameTextBlock_ItemName;                           // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        FlameTextBlock_Rarity;                             // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_76;                                          // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_120;                                         // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_226;                                     // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CharityBox_Tile_C*                  UI_CharityBox_Tile;                                // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_Content;                               // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_92;                                 // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnClicked;                                         // 0x0330(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnPressed;                                         // 0x0340(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UWidget*                                FocusedRow;                                        // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnClicked__DelegateSignature();
	void OnPressed__DelegateSignature();
	void ExecuteUbergraph_UI_CharityBox_Rewards(int32 EntryPoint);
	void Construct();
	void OnChildFocusReceived(class UWidget* InWidget);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	void FillData(TArray<struct FCloudCharityBoxSeasonMilestoneInfo>& MilestoneInfo, int32 DonatedFood, int32* FoodToNextMilestone);
	void CallOnClicked();
	void CallOnPressed();
	void ClearData();
	void InsertSort(TArray<struct FCloudCharityBoxSeasonMilestoneInfo>& Array);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_CharityBox_Rewards_C">();
	}
	static class UUI_CharityBox_Rewards_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_CharityBox_Rewards_C>();
	}
};
static_assert(alignof(UUI_CharityBox_Rewards_C) == 0x000008, "Wrong alignment on UUI_CharityBox_Rewards_C");
static_assert(sizeof(UUI_CharityBox_Rewards_C) == 0x000358, "Wrong size on UUI_CharityBox_Rewards_C");
static_assert(offsetof(UUI_CharityBox_Rewards_C, UberGraphFrame) == 0x0002D8, "Member 'UUI_CharityBox_Rewards_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, FlameTextBlock_227) == 0x0002E0, "Member 'UUI_CharityBox_Rewards_C::FlameTextBlock_227' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, FlameTextBlock_Category) == 0x0002E8, "Member 'UUI_CharityBox_Rewards_C::FlameTextBlock_Category' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, FlameTextBlock_ItemName) == 0x0002F0, "Member 'UUI_CharityBox_Rewards_C::FlameTextBlock_ItemName' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, FlameTextBlock_Rarity) == 0x0002F8, "Member 'UUI_CharityBox_Rewards_C::FlameTextBlock_Rarity' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, Image_76) == 0x000300, "Member 'UUI_CharityBox_Rewards_C::Image_76' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, Image_120) == 0x000308, "Member 'UUI_CharityBox_Rewards_C::Image_120' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, ScrollBox_226) == 0x000310, "Member 'UUI_CharityBox_Rewards_C::ScrollBox_226' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, UI_CharityBox_Tile) == 0x000318, "Member 'UUI_CharityBox_Rewards_C::UI_CharityBox_Tile' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, VerticalBox_Content) == 0x000320, "Member 'UUI_CharityBox_Rewards_C::VerticalBox_Content' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, WidgetSwitcher_92) == 0x000328, "Member 'UUI_CharityBox_Rewards_C::WidgetSwitcher_92' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, OnClicked) == 0x000330, "Member 'UUI_CharityBox_Rewards_C::OnClicked' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, OnPressed) == 0x000340, "Member 'UUI_CharityBox_Rewards_C::OnPressed' has a wrong offset!");
static_assert(offsetof(UUI_CharityBox_Rewards_C, FocusedRow) == 0x000350, "Member 'UUI_CharityBox_Rewards_C::FocusedRow' has a wrong offset!");

}

