#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CharityBox_Tab

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UI_CharityBox_Tab.UI_CharityBox_Tab_C.ExecuteUbergraph_UI_CharityBox_Tab
// 0x0070 (0x0070 - 0x0000)
struct UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0008(0x0018)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0020(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0048(0x0028)()
};
static_assert(alignof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab) == 0x000008, "Wrong alignment on UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab");
static_assert(sizeof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab) == 0x000070, "Wrong size on UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab");
static_assert(offsetof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab, EntryPoint) == 0x000000, "Member 'UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab, K2Node_Event_IsDesignTime) == 0x000004, "Member 'UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab, CallFunc_TextToUpper_ReturnValue) == 0x000008, "Member 'UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab, K2Node_MakeStruct_SlateColor) == 0x000020, "Member 'UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab, K2Node_MakeStruct_SlateColor_1) == 0x000048, "Member 'UI_CharityBox_Tab_C_ExecuteUbergraph_UI_CharityBox_Tab::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");

// Function UI_CharityBox_Tab.UI_CharityBox_Tab_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_CharityBox_Tab_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_CharityBox_Tab_C_PreConstruct) == 0x000001, "Wrong alignment on UI_CharityBox_Tab_C_PreConstruct");
static_assert(sizeof(UI_CharityBox_Tab_C_PreConstruct) == 0x000001, "Wrong size on UI_CharityBox_Tab_C_PreConstruct");
static_assert(offsetof(UI_CharityBox_Tab_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_CharityBox_Tab_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

