#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FavoriteOutfitSubMenu

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_FavoriteOutfitSubMenu.UI_FavoriteOutfitSubMenu_C
// 0x00A8 (0x0398 - 0x02F0)
class UUI_FavoriteOutfitSubMenu_C final : public UModalWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ArrowHighlight_4;                                  // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ArrowHighlight_3;                                  // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ArrowHighlight_2;                                  // 0x0308(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ArrowHighlight_1;                                  // 0x0310(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_Loadout_Button_C*                   EquipOutfitSetButton;                              // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_48;                                          // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                InputActionCancel;                                 // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                InputActionConfirm;                                // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_0;                                         // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Loadout_Button_C*                   SaveOutfitSetButton;                               // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        TitleText;                                         // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ABP_InteractableWardrobe_C*             WardrobeBP;                                        // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         OutfitIndex;                                       // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         PosterID_Using_thisOutfitSet;                      // 0x0364(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TEMP_PosterID_Using_thisOutfitSet;                 // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TEMP_SwappedPosterID_ToRender;                     // 0x036C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         UsedTemplateID;                                    // 0x0370(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TEMP_UsedTemplateID;                               // 0x0374(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CountOfPosters;                                    // 0x0378(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CountOfTemplates;                                  // 0x037C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_FavoriteOutfitsListButton_C*        OutfitSetListButton;                               // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UUI_FavoriteOutfitSet_C*                FavoriteOutfitSetParent;                           // 0x0388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UUI_IdleWidget_C*                       IdleWidget;                                        // 0x0390(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_FavoriteOutfitSubMenu(int32 EntryPoint);
	void BndEvt__InputActionCancel_K2Node_ComponentBoundEvent_2_OnActionPressedEvent__DelegateSignature();
	void RemoveIdleWidgetEvent();
	void NewCustomizationLoaded(class AHumanCharacter* Sender, class UInventoryCustomizationComponent* Inventory);
	void SaveOutfitButtonPressed(class UButton* Sender);
	void EquipOutfitSetButtonPressed(class UButton* Sender);
	void Construct();
	void PreConstruct(bool IsDesignTime);

	class UWidget* GetWidgetToFocus() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_FavoriteOutfitSubMenu_C">();
	}
	static class UUI_FavoriteOutfitSubMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_FavoriteOutfitSubMenu_C>();
	}
};
static_assert(alignof(UUI_FavoriteOutfitSubMenu_C) == 0x000008, "Wrong alignment on UUI_FavoriteOutfitSubMenu_C");
static_assert(sizeof(UUI_FavoriteOutfitSubMenu_C) == 0x000398, "Wrong size on UUI_FavoriteOutfitSubMenu_C");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, UberGraphFrame) == 0x0002F0, "Member 'UUI_FavoriteOutfitSubMenu_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, ArrowHighlight_4) == 0x0002F8, "Member 'UUI_FavoriteOutfitSubMenu_C::ArrowHighlight_4' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, ArrowHighlight_3) == 0x000300, "Member 'UUI_FavoriteOutfitSubMenu_C::ArrowHighlight_3' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, ArrowHighlight_2) == 0x000308, "Member 'UUI_FavoriteOutfitSubMenu_C::ArrowHighlight_2' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, ArrowHighlight_1) == 0x000310, "Member 'UUI_FavoriteOutfitSubMenu_C::ArrowHighlight_1' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, EquipOutfitSetButton) == 0x000318, "Member 'UUI_FavoriteOutfitSubMenu_C::EquipOutfitSetButton' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, Image) == 0x000320, "Member 'UUI_FavoriteOutfitSubMenu_C::Image' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, Image_48) == 0x000328, "Member 'UUI_FavoriteOutfitSubMenu_C::Image_48' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, InputActionCancel) == 0x000330, "Member 'UUI_FavoriteOutfitSubMenu_C::InputActionCancel' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, InputActionConfirm) == 0x000338, "Member 'UUI_FavoriteOutfitSubMenu_C::InputActionConfirm' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, Overlay_0) == 0x000340, "Member 'UUI_FavoriteOutfitSubMenu_C::Overlay_0' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, SaveOutfitSetButton) == 0x000348, "Member 'UUI_FavoriteOutfitSubMenu_C::SaveOutfitSetButton' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, TitleText) == 0x000350, "Member 'UUI_FavoriteOutfitSubMenu_C::TitleText' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, WardrobeBP) == 0x000358, "Member 'UUI_FavoriteOutfitSubMenu_C::WardrobeBP' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, OutfitIndex) == 0x000360, "Member 'UUI_FavoriteOutfitSubMenu_C::OutfitIndex' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, PosterID_Using_thisOutfitSet) == 0x000364, "Member 'UUI_FavoriteOutfitSubMenu_C::PosterID_Using_thisOutfitSet' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, TEMP_PosterID_Using_thisOutfitSet) == 0x000368, "Member 'UUI_FavoriteOutfitSubMenu_C::TEMP_PosterID_Using_thisOutfitSet' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, TEMP_SwappedPosterID_ToRender) == 0x00036C, "Member 'UUI_FavoriteOutfitSubMenu_C::TEMP_SwappedPosterID_ToRender' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, UsedTemplateID) == 0x000370, "Member 'UUI_FavoriteOutfitSubMenu_C::UsedTemplateID' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, TEMP_UsedTemplateID) == 0x000374, "Member 'UUI_FavoriteOutfitSubMenu_C::TEMP_UsedTemplateID' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, CountOfPosters) == 0x000378, "Member 'UUI_FavoriteOutfitSubMenu_C::CountOfPosters' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, CountOfTemplates) == 0x00037C, "Member 'UUI_FavoriteOutfitSubMenu_C::CountOfTemplates' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, OutfitSetListButton) == 0x000380, "Member 'UUI_FavoriteOutfitSubMenu_C::OutfitSetListButton' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, FavoriteOutfitSetParent) == 0x000388, "Member 'UUI_FavoriteOutfitSubMenu_C::FavoriteOutfitSetParent' has a wrong offset!");
static_assert(offsetof(UUI_FavoriteOutfitSubMenu_C, IdleWidget) == 0x000390, "Member 'UUI_FavoriteOutfitSubMenu_C::IdleWidget' has a wrong offset!");

}

