#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FavoriteOutfitsListButton_Empty

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty
// 0x0028 (0x0028 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UButton*                                K2Node_ComponentBoundEvent_Sender_2;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UButton*                                K2Node_ComponentBoundEvent_Sender_1;               // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UButton*                                K2Node_ComponentBoundEvent_Sender;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty) == 0x000008, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty) == 0x000028, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty, EntryPoint) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty, K2Node_ComponentBoundEvent_Sender_2) == 0x000008, "Member 'UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty::K2Node_ComponentBoundEvent_Sender_2' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty, K2Node_ComponentBoundEvent_Sender_1) == 0x000010, "Member 'UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty::K2Node_ComponentBoundEvent_Sender_1' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty, K2Node_ComponentBoundEvent_Sender) == 0x000018, "Member 'UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty::K2Node_ComponentBoundEvent_Sender' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty, K2Node_Event_IsDesignTime) == 0x000020, "Member 'UI_FavoriteOutfitsListButton_Empty_C_ExecuteUbergraph_UI_FavoriteOutfitsListButton_Empty::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_PreConstruct) == 0x000001, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_PreConstruct");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_PreConstruct) == 0x000001, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_PreConstruct");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature final
{
public:
	class UButton*                                Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature) == 0x000008, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature, Sender) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature::Sender' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature final
{
public:
	class UButton*                                Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature) == 0x000008, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature, Sender) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_OnButtonFocusEvent__DelegateSignature::Sender' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature final
{
public:
	class UButton*                                Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature) == 0x000008, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature, Sender) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnButtonFocusEvent__DelegateSignature::Sender' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.InitializeListButton
// 0x00A0 (0x00A0 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton final
{
public:
	int32                                         CurrentOutfitCount;                                // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NextLVL_ToIncrease;                                // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentMax;                                        // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentPosterCount;                                // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0060(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0070(0x0018)()
	int32                                         CallFunc_GetPossibleOutfitCounts_CurrentMax_OutfitSetSlotCount; // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPossibleOutfitCounts_NextLVL_ToIncrease; // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetPossibleOutfitCounts_ShouldBeEmpty;    // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetMaxOutfitSetCount_OutfitSetsCurrentMaxCount; // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetMaxOutfitSetCount_TotalMax;            // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton) == 0x000008, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton) == 0x0000A0, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CurrentOutfitCount) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CurrentOutfitCount' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, NextLVL_ToIncrease) == 0x000004, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::NextLVL_ToIncrease' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CurrentMax) == 0x000008, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CurrentMax' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CurrentPosterCount) == 0x00000C, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CurrentPosterCount' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000010, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, K2Node_MakeStruct_FormatArgumentData) == 0x000018, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_IsValid_ReturnValue) == 0x000058, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, K2Node_MakeArray_Array) == 0x000060, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_Format_ReturnValue) == 0x000070, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_GetPossibleOutfitCounts_CurrentMax_OutfitSetSlotCount) == 0x000088, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_GetPossibleOutfitCounts_CurrentMax_OutfitSetSlotCount' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_GetPossibleOutfitCounts_NextLVL_ToIncrease) == 0x00008C, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_GetPossibleOutfitCounts_NextLVL_ToIncrease' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_GetPossibleOutfitCounts_ShouldBeEmpty) == 0x000090, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_GetPossibleOutfitCounts_ShouldBeEmpty' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_GetMaxOutfitSetCount_OutfitSetsCurrentMaxCount) == 0x000094, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_GetMaxOutfitSetCount_OutfitSetsCurrentMaxCount' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton, CallFunc_GetMaxOutfitSetCount_TotalMax) == 0x000098, "Member 'UI_FavoriteOutfitsListButton_Empty_C_InitializeListButton::CallFunc_GetMaxOutfitSetCount_TotalMax' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.Toggle Focus
// 0x0005 (0x0005 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus final
{
public:
	bool                                          bShouldBeFocused;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus) == 0x000001, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus) == 0x000005, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus, bShouldBeFocused) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus::bShouldBeFocused' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus, Temp_bool_Variable) == 0x000001, "Member 'UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus, Temp_byte_Variable) == 0x000002, "Member 'UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus, Temp_byte_Variable_1) == 0x000003, "Member 'UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus, K2Node_Select_Default) == 0x000004, "Member 'UI_FavoriteOutfitsListButton_Empty_C_Toggle_Focus::K2Node_Select_Default' has a wrong offset!");

// Function UI_FavoriteOutfitsListButton_Empty.UI_FavoriteOutfitsListButton_Empty_C.GetPossibleOutfitCounts
// 0x00B8 (0x00B8 - 0x0000)
struct UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts final
{
public:
	int32                                         CurrentMax_OutfitSetSlotCount;                     // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NextLVL_ToIncrease;                                // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldBeEmpty;                                     // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CurrentMaxOutfitSetCount;                          // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 CallFunc_Map_Keys_Keys;                            // 0x0028(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Get_Item;                           // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Map_Find_Value;                           // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_PlayerController_Shelter_C*         K2Node_DynamicCast_AsBP_Player_Controller_Shelter; // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AStash*                                 CallFunc_GetStash_ReturnValue;                     // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetRepairLevel_ReturnValue;               // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Map_Find_Value_1;                         // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Map_Find_Value_2;                         // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_85[0x3];                                       // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts) == 0x000008, "Wrong alignment on UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts");
static_assert(sizeof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts) == 0x0000B8, "Wrong size on UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CurrentMax_OutfitSetSlotCount) == 0x000000, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CurrentMax_OutfitSetSlotCount' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, NextLVL_ToIncrease) == 0x000004, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::NextLVL_ToIncrease' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, ShouldBeEmpty) == 0x000008, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::ShouldBeEmpty' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CurrentMaxOutfitSetCount) == 0x00000C, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CurrentMaxOutfitSetCount' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000014, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Add_IntInt_ReturnValue_1) == 0x000020, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Keys_Keys) == 0x000028, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Array_Get_Item) == 0x000038, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Array_Length_ReturnValue) == 0x00003C, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Find_Value) == 0x000044, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Find_ReturnValue) == 0x000048, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000049, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_IsValid_ReturnValue) == 0x00004A, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_GetOwningPlayer_ReturnValue) == 0x000050, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, K2Node_DynamicCast_AsBP_Player_Controller_Shelter) == 0x000058, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::K2Node_DynamicCast_AsBP_Player_Controller_Shelter' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, K2Node_DynamicCast_bSuccess) == 0x000060, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_GetStash_ReturnValue) == 0x000068, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_GetStash_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_GetRepairLevel_ReturnValue) == 0x000070, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_GetRepairLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Find_Value_1) == 0x000074, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Find_ReturnValue_1) == 0x000078, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Add_IntInt_ReturnValue_2) == 0x00007C, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Find_Value_2) == 0x000080, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Map_Find_ReturnValue_2) == 0x000084, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Conv_IntToString_ReturnValue) == 0x000088, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Concat_StrStr_ReturnValue) == 0x000098, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0000A8, "Member 'UI_FavoriteOutfitsListButton_Empty_C_GetPossibleOutfitCounts::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");

}

