#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FavoriteOutfitSet

#include "Basic.hpp"

#include "UI_FavoriteOutfitSet_classes.hpp"
#include "UI_FavoriteOutfitSet_parameters.hpp"


namespace SDK
{

// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.ExecuteUbergraph_UI_FavoriteOutfitSet
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::ExecuteUbergraph_UI_FavoriteOutfitSet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "ExecuteUbergraph_UI_FavoriteOutfitSet");

	Params::UI_FavoriteOutfitSet_C_ExecuteUbergraph_UI_FavoriteOutfitSet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.CheckForChallengesUI_PopUp
// (BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::CheckForChallengesUI_PopUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "CheckForChallengesUI_PopUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.UpdateLightIndicator
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Hidden                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_FavoriteOutfitSet_C::UpdateLightIndicator(bool bEnabled, bool Hidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "UpdateLightIndicator");

	Params::UI_FavoriteOutfitSet_C_UpdateLightIndicator Parms{};

	Parms.bEnabled = bEnabled;
	Parms.Hidden = Hidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "Tick");

	Params::UI_FavoriteOutfitSet_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.CloseObstructingUIs
// (BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::CloseObstructingUIs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "CloseObstructingUIs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.ExitPosterPreview
// (BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::ExitPosterPreview()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "ExitPosterPreview");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.PosterUpdated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_SeparatePoster_C*             Poster                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::PosterUpdated(class ABP_SeparatePoster_C* Poster)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "PosterUpdated");

	Params::UI_FavoriteOutfitSet_C_PosterUpdated Parms{};

	Parms.Poster = Poster;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.UpdateUI_PosterPreview
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   OutfitSetID                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PosterID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::UpdateUI_PosterPreview(int32 OutfitSetID, int32 PosterID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "UpdateUI_PosterPreview");

	Params::UI_FavoriteOutfitSet_C_UpdateUI_PosterPreview Parms{};

	Parms.OutfitSetID = OutfitSetID;
	Parms.PosterID = PosterID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.OutfitSetButtonFocusedEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   OutfitID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::OutfitSetButtonFocusedEvent(int32 OutfitID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "OutfitSetButtonFocusedEvent");

	Params::UI_FavoriteOutfitSet_C_OutfitSetButtonFocusedEvent Parms{};

	Parms.OutfitID = OutfitID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.PosterListButtonSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_FavoriteOutfitPosterListButton_C*PosterListButton                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::PosterListButtonSelected(class UUI_FavoriteOutfitPosterListButton_C* PosterListButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "PosterListButtonSelected");

	Params::UI_FavoriteOutfitSet_C_PosterListButtonSelected Parms{};

	Parms.PosterListButton = PosterListButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.EmptyRowSelected
// (BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::EmptyRowSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "EmptyRowSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.PreviewButtonPressed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   OutfitIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::PreviewButtonPressed(int32 OutfitIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "PreviewButtonPressed");

	Params::UI_FavoriteOutfitSet_C_PreviewButtonPressed Parms{};

	Parms.OutfitIndex = OutfitIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.BndEvt__CosmeticsButton_K2Node_ComponentBoundEvent_4_OnActionPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_FavoriteOutfitSet_C::BndEvt__CosmeticsButton_K2Node_ComponentBoundEvent_4_OnActionPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "BndEvt__CosmeticsButton_K2Node_ComponentBoundEvent_4_OnActionPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.PosterListButtonFocused
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_FavoriteOutfitPosterListButton_C*PosterListButton                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::PosterListButtonFocused(class UUI_FavoriteOutfitPosterListButton_C* PosterListButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "PosterListButtonFocused");

	Params::UI_FavoriteOutfitSet_C_PosterListButtonFocused Parms{};

	Parms.PosterListButton = PosterListButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.EscapeWardrobe
// (BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::EscapeWardrobe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "EscapeWardrobe");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.ExitWardrobeUI
// (BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::ExitWardrobeUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "ExitWardrobeUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.FavoriteOutfitSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_FavoriteOutfitsListButton_C*  Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::FavoriteOutfitSelected(class UUI_FavoriteOutfitsListButton_C* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "FavoriteOutfitSelected");

	Params::UI_FavoriteOutfitSet_C_FavoriteOutfitSelected Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.BndEvt__BackButton_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_FavoriteOutfitSet_C::BndEvt__BackButton_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "BndEvt__BackButton_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_FavoriteOutfitSet_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "PreConstruct");

	Params::UI_FavoriteOutfitSet_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.GetListButtonByOutfitSetID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   OutfitSetID                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUI_FavoriteOutfitsListButton_C*  ListButton                                             (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FavoriteOutfitSet_C::GetListButtonByOutfitSetID(int32 OutfitSetID, class UUI_FavoriteOutfitsListButton_C** ListButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "GetListButtonByOutfitSetID");

	Params::UI_FavoriteOutfitSet_C_GetListButtonByOutfitSetID Parms{};

	Parms.OutfitSetID = OutfitSetID;

	UObject::ProcessEvent(Func, &Parms);

	if (ListButton != nullptr)
		*ListButton = Parms.ListButton;
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.FillOutfitSetButtons
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::FillOutfitSetButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "FillOutfitSetButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.AddOutfitSetSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::AddOutfitSetSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "AddOutfitSetSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.RenderUnrenderedPosters
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_FavoriteOutfitSet_C::RenderUnrenderedPosters()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "RenderUnrenderedPosters");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_FavoriteOutfitSet.UI_FavoriteOutfitSet_C.GetWidgetToFocus
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUI_FavoriteOutfitSet_C::GetWidgetToFocus() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FavoriteOutfitSet_C", "GetWidgetToFocus");

	Params::UI_FavoriteOutfitSet_C_GetWidgetToFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

