#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Leaderboards_Row

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Leaderboards_Row.UI_Leaderboards_Row_C
// 0x0058 (0x0310 - 0x02B8)
class UUI_Leaderboards_Row_C final : public UFlameWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFlameTextBlock*                        FlameTextBlock_Donated;                            // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        FlameTextBlock_Outlander;                          // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        FlameTextBlock_Percentage;                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        FlameTextBlock_Rank;                               // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Back0;                                       // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Back1;                                       // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Back2;                                       // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Me;                                          // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Team;                                        // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsTitle;                                           // 0x0308(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          IsMe;                                              // 0x0309(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          IsFriend;                                          // 0x030A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          ShowRank;                                          // 0x030B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_Leaderboards_Row(int32 EntryPoint);
	void FillUI(bool IsMe_0, bool IsFriend_0, bool ShowRank_0, int32 Rank, const class FText& Name_0, float Percentage, int32 Donated);
	void UpdateVisual();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Leaderboards_Row_C">();
	}
	static class UUI_Leaderboards_Row_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Leaderboards_Row_C>();
	}
};
static_assert(alignof(UUI_Leaderboards_Row_C) == 0x000008, "Wrong alignment on UUI_Leaderboards_Row_C");
static_assert(sizeof(UUI_Leaderboards_Row_C) == 0x000310, "Wrong size on UUI_Leaderboards_Row_C");
static_assert(offsetof(UUI_Leaderboards_Row_C, UberGraphFrame) == 0x0002B8, "Member 'UUI_Leaderboards_Row_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, FlameTextBlock_Donated) == 0x0002C0, "Member 'UUI_Leaderboards_Row_C::FlameTextBlock_Donated' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, FlameTextBlock_Outlander) == 0x0002C8, "Member 'UUI_Leaderboards_Row_C::FlameTextBlock_Outlander' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, FlameTextBlock_Percentage) == 0x0002D0, "Member 'UUI_Leaderboards_Row_C::FlameTextBlock_Percentage' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, FlameTextBlock_Rank) == 0x0002D8, "Member 'UUI_Leaderboards_Row_C::FlameTextBlock_Rank' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, Image_Back0) == 0x0002E0, "Member 'UUI_Leaderboards_Row_C::Image_Back0' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, Image_Back1) == 0x0002E8, "Member 'UUI_Leaderboards_Row_C::Image_Back1' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, Image_Back2) == 0x0002F0, "Member 'UUI_Leaderboards_Row_C::Image_Back2' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, Image_Me) == 0x0002F8, "Member 'UUI_Leaderboards_Row_C::Image_Me' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, Image_Team) == 0x000300, "Member 'UUI_Leaderboards_Row_C::Image_Team' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, IsTitle) == 0x000308, "Member 'UUI_Leaderboards_Row_C::IsTitle' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, IsMe) == 0x000309, "Member 'UUI_Leaderboards_Row_C::IsMe' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, IsFriend) == 0x00030A, "Member 'UUI_Leaderboards_Row_C::IsFriend' has a wrong offset!");
static_assert(offsetof(UUI_Leaderboards_Row_C, ShowRank) == 0x00030B, "Member 'UUI_Leaderboards_Row_C::ShowRank' has a wrong offset!");

}

