#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Leaderboards

#include "Basic.hpp"

#include "UI_Leaderboards_classes.hpp"
#include "UI_Leaderboards_parameters.hpp"


namespace SDK
{

// Function UI_Leaderboards.UI_Leaderboards_C.PlayerStatUpdated__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Stats                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::PlayerStatUpdated__DelegateSignature(int32 Stats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "PlayerStatUpdated__DelegateSignature");

	Params::UI_Leaderboards_C_PlayerStatUpdated__DelegateSignature Parms{};

	Parms.Stats = Stats;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.UpdateStatsDelayed__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::UpdateStatsDelayed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "UpdateStatsDelayed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.ExecuteUbergraph_UI_Leaderboards
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::ExecuteUbergraph_UI_Leaderboards(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "ExecuteUbergraph_UI_Leaderboards");

	Params::UI_Leaderboards_C_ExecuteUbergraph_UI_Leaderboards Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.OnUpdateStatsCooldown
// (BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::OnUpdateStatsCooldown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "OnUpdateStatsCooldown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.ClearCachedLeaderBoards
// (BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::ClearCachedLeaderBoards()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "ClearCachedLeaderBoards");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.DelayInProgress
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Leaderboards_C::DelayInProgress(float Delay, bool Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "DelayInProgress");

	Params::UI_Leaderboards_C_DelayInProgress Parms{};

	Parms.Delay = Delay;
	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.Upppp
// (BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::Upppp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "Upppp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.Downnnn
// (BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::Downnnn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "Downnnn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.Update Stats
// (BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::Update_Stats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "Update Stats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.BndEvt__UI_GamepadActionWidget_C_1_K2Node_ComponentBoundEvent_3_OnActionPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Leaderboards_C::BndEvt__UI_GamepadActionWidget_C_1_K2Node_ComponentBoundEvent_3_OnActionPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "BndEvt__UI_GamepadActionWidget_C_1_K2Node_ComponentBoundEvent_3_OnActionPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.BndEvt__UI_GamepadActionWidget_C_0_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Leaderboards_C::BndEvt__UI_GamepadActionWidget_C_0_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "BndEvt__UI_GamepadActionWidget_C_0_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.BndEvt__UI_GamepadActionWidget_C_144_K2Node_ComponentBoundEvent_2_OnActionPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Leaderboards_C::BndEvt__UI_GamepadActionWidget_C_144_K2Node_ComponentBoundEvent_2_OnActionPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "BndEvt__UI_GamepadActionWidget_C_144_K2Node_ComponentBoundEvent_2_OnActionPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.BndEvt__UI_GamepadActionWidget_C_146_K2Node_ComponentBoundEvent_1_OnActionPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Leaderboards_C::BndEvt__UI_GamepadActionWidget_C_146_K2Node_ComponentBoundEvent_1_OnActionPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "BndEvt__UI_GamepadActionWidget_C_146_K2Node_ComponentBoundEvent_1_OnActionPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Leaderboards_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.OnSyncFinished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Succeeded                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   RequestId                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::OnSyncFinished(bool Succeeded, int32 RequestId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "OnSyncFinished");

	Params::UI_Leaderboards_C_OnSyncFinished Parms{};

	Parms.Succeeded = Succeeded;
	Parms.RequestId = RequestId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.OnLeaderboardDataRed
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Succeeded                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   RequestId                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLeaderboardReadContext          BoardContext                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// struct FLeaderboardData                 LeaderboardData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::OnLeaderboardDataRed(bool Succeeded, int32 RequestId, const struct FLeaderboardReadContext& BoardContext, const struct FLeaderboardData& LeaderboardData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "OnLeaderboardDataRed");

	Params::UI_Leaderboards_C_OnLeaderboardDataRed Parms{};

	Parms.Succeeded = Succeeded;
	Parms.RequestId = RequestId;
	Parms.BoardContext = std::move(BoardContext);
	Parms.LeaderboardData = std::move(LeaderboardData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Leaderboards_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Leaderboards_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "PreConstruct");

	Params::UI_Leaderboards_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.CreateRow
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FLeaderboardDataRow              LeaderboardDataRow                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    IsMe                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsFriend                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    ShowRank                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   RenumberedRank                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::CreateRow(const struct FLeaderboardDataRow& LeaderboardDataRow, bool IsMe, bool IsFriend, bool ShowRank, int32 RenumberedRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "CreateRow");

	Params::UI_Leaderboards_C_CreateRow Parms{};

	Parms.LeaderboardDataRow = std::move(LeaderboardDataRow);
	Parms.IsMe = IsMe;
	Parms.IsFriend = IsFriend;
	Parms.ShowRank = ShowRank;
	Parms.RenumberedRank = RenumberedRank;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.FillData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowFriends                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Leaderboards_C::FillData(bool ShowFriends)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "FillData");

	Params::UI_Leaderboards_C_FillData Parms{};

	Parms.ShowFriends = ShowFriends;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetFriends
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::GetFriends()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetFriends");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetAllAroundUser
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::GetAllAroundUser()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetAllAroundUser");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetArroundRank
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Start_Rank                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::GetArroundRank(int32 Start_Rank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetArroundRank");

	Params::UI_Leaderboards_C_GetArroundRank Parms{};

	Parms.Start_Rank = Start_Rank;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.IsPlayerFriend
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FUniqueNetIdRepl                 Userid                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    IsFriend                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Leaderboards_C::IsPlayerFriend(const struct FUniqueNetIdRepl& Userid, bool* IsFriend)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "IsPlayerFriend");

	Params::UI_Leaderboards_C_IsPlayerFriend Parms{};

	Parms.Userid = std::move(Userid);

	UObject::ProcessEvent(Func, &Parms);

	if (IsFriend != nullptr)
		*IsFriend = Parms.IsFriend;
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetRankLeaderboardPosition
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FLeaderboardDataRow>      LeaderboardData                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   FirstIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LastIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TestedRank                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::GetRankLeaderboardPosition(TArray<struct FLeaderboardDataRow>& LeaderboardData, int32 FirstIndex, int32 LastIndex, int32 TestedRank, int32* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetRankLeaderboardPosition");

	Params::UI_Leaderboards_C_GetRankLeaderboardPosition Parms{};

	Parms.LeaderboardData = std::move(LeaderboardData);
	Parms.FirstIndex = FirstIndex;
	Parms.LastIndex = LastIndex;
	Parms.TestedRank = TestedRank;

	UObject::ProcessEvent(Func, &Parms);

	LeaderboardData = std::move(Parms.LeaderboardData);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function UI_Leaderboards.UI_Leaderboards_C.SetCurrentPlayerLeaderboardData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FLeaderboardDataRow>      LeaderboardRowData                                     (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::SetCurrentPlayerLeaderboardData(TArray<struct FLeaderboardDataRow>& LeaderboardRowData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "SetCurrentPlayerLeaderboardData");

	Params::UI_Leaderboards_C_SetCurrentPlayerLeaderboardData Parms{};

	Parms.LeaderboardRowData = std::move(LeaderboardRowData);

	UObject::ProcessEvent(Func, &Parms);

	LeaderboardRowData = std::move(Parms.LeaderboardRowData);
}


// Function UI_Leaderboards.UI_Leaderboards_C.SetLeaderboardName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           LeaderboardName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   DonatedFood_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::SetLeaderboardName(const class FString& LeaderboardName, int32 DonatedFood_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "SetLeaderboardName");

	Params::UI_Leaderboards_C_SetLeaderboardName Parms{};

	Parms.LeaderboardName = std::move(LeaderboardName);
	Parms.DonatedFood_0 = DonatedFood_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.IsPlayerCurrent
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FUniqueNetIdRepl                 Userid                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UUI_Leaderboards_C::IsPlayerCurrent(const struct FUniqueNetIdRepl& Userid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "IsPlayerCurrent");

	Params::UI_Leaderboards_C_IsPlayerCurrent Parms{};

	Parms.Userid = std::move(Userid);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Leaderboards.UI_Leaderboards_C.SetRequestInProgress
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RequestInProgress_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Leaderboards_C::SetRequestInProgress(bool RequestInProgress_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "SetRequestInProgress");

	Params::UI_Leaderboards_C_SetRequestInProgress Parms{};

	Parms.RequestInProgress_0 = RequestInProgress_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.SetSyncInProgress
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SyncInProgress_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_Leaderboards_C::SetSyncInProgress(bool SyncInProgress_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "SetSyncInProgress");

	Params::UI_Leaderboards_C_SetSyncInProgress Parms{};

	Parms.SyncInProgress_0 = SyncInProgress_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetStepWaitingStep
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   WaitFor                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Leaderboards_C::GetStepWaitingStep(float* WaitFor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetStepWaitingStep");

	Params::UI_Leaderboards_C_GetStepWaitingStep Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (WaitFor != nullptr)
		*WaitFor = Parms.WaitFor;
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetThreePagesWorthOfLeaderBoardsAroundUser
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::GetThreePagesWorthOfLeaderBoardsAroundUser()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetThreePagesWorthOfLeaderBoardsAroundUser");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.FillData_modif
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowFriends                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<struct FLeaderboardDataRow>      LeaderBoardDataRows                                    (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::FillData_modif(bool ShowFriends, TArray<struct FLeaderboardDataRow>& LeaderBoardDataRows)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "FillData_modif");

	Params::UI_Leaderboards_C_FillData_modif Parms{};

	Parms.ShowFriends = ShowFriends;
	Parms.LeaderBoardDataRows = std::move(LeaderBoardDataRows);

	UObject::ProcessEvent(Func, &Parms);

	LeaderBoardDataRows = std::move(Parms.LeaderBoardDataRows);
}


// Function UI_Leaderboards.UI_Leaderboards_C.DrawUpdateEntries
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FLeaderboardDataRow>      LeaderboardData                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::DrawUpdateEntries(TArray<struct FLeaderboardDataRow>& LeaderboardData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "DrawUpdateEntries");

	Params::UI_Leaderboards_C_DrawUpdateEntries Parms{};

	Parms.LeaderboardData = std::move(LeaderboardData);

	UObject::ProcessEvent(Func, &Parms);

	LeaderboardData = std::move(Parms.LeaderboardData);
}


// Function UI_Leaderboards.UI_Leaderboards_C.RemoveLeaderboardContent
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::RemoveLeaderboardContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "RemoveLeaderboardContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.UpdateLeaderboardVariables
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FLeaderboardDataRow>      LeaderboardData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::UpdateLeaderboardVariables(const TArray<struct FLeaderboardDataRow>& LeaderboardData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "UpdateLeaderboardVariables");

	Params::UI_Leaderboards_C_UpdateLeaderboardVariables Parms{};

	Parms.LeaderboardData = std::move(LeaderboardData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Leaderboards.UI_Leaderboards_C.FillData_Friends
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowFriends                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<struct FLeaderboardDataRow>      LeaderBoardDataRows                                    (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::FillData_Friends(bool ShowFriends, TArray<struct FLeaderboardDataRow>& LeaderBoardDataRows)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "FillData_Friends");

	Params::UI_Leaderboards_C_FillData_Friends Parms{};

	Parms.ShowFriends = ShowFriends;
	Parms.LeaderBoardDataRows = std::move(LeaderBoardDataRows);

	UObject::ProcessEvent(Func, &Parms);

	LeaderBoardDataRows = std::move(Parms.LeaderBoardDataRows);
}


// Function UI_Leaderboards.UI_Leaderboards_C.UpdateLeaderboardData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELeaderboardType                        Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FLeaderboardDataRow>      LeaderboardRowData                                     (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Leaderboards_C::UpdateLeaderboardData(ELeaderboardType Selection, TArray<struct FLeaderboardDataRow>& LeaderboardRowData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "UpdateLeaderboardData");

	Params::UI_Leaderboards_C_UpdateLeaderboardData Parms{};

	Parms.Selection = Selection;
	Parms.LeaderboardRowData = std::move(LeaderboardRowData);

	UObject::ProcessEvent(Func, &Parms);

	LeaderboardRowData = std::move(Parms.LeaderboardRowData);
}


// Function UI_Leaderboards.UI_Leaderboards_C.UpdateScrollOpacity
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Leaderboards_C::UpdateScrollOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "UpdateScrollOpacity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Leaderboards.UI_Leaderboards_C.FakeNumberRank
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FLeaderboardDataRow>      Leaderboard                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TMap<struct FUniqueNetIdRepl, int32>    Renumbered_IDs                                         (Parm, OutParm)

void UUI_Leaderboards_C::FakeNumberRank(TArray<struct FLeaderboardDataRow>& Leaderboard, TMap<struct FUniqueNetIdRepl, int32>* Renumbered_IDs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "FakeNumberRank");

	Params::UI_Leaderboards_C_FakeNumberRank Parms{};

	Parms.Leaderboard = std::move(Leaderboard);

	UObject::ProcessEvent(Func, &Parms);

	Leaderboard = std::move(Parms.Leaderboard);

	if (Renumbered_IDs != nullptr)
		*Renumbered_IDs = std::move(Parms.Renumbered_IDs);
}


// Function UI_Leaderboards.UI_Leaderboards_C.GetCacheDelay
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FTimespan                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FTimespan UUI_Leaderboards_C::GetCacheDelay() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Leaderboards_C", "GetCacheDelay");

	Params::UI_Leaderboards_C_GetCacheDelay Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

