#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_WeaponGridSlot_2

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function UI_WeaponGridSlot_2.UI_WeaponGridSlot_2_C.ExecuteUbergraph_UI_WeaponGridSlot_2
// 0x0030 (0x0030 - 0x0000)
struct UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UButton*                                K2Node_ComponentBoundEvent_Sender_2;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UButton*                                K2Node_ComponentBoundEvent_Sender_1;               // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UButton*                                K2Node_ComponentBoundEvent_Sender;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2) == 0x000008, "Wrong alignment on UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2");
static_assert(sizeof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2) == 0x000030, "Wrong size on UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2");
static_assert(offsetof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2, EntryPoint) == 0x000000, "Member 'UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2, K2Node_ComponentBoundEvent_Sender_2) == 0x000008, "Member 'UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2::K2Node_ComponentBoundEvent_Sender_2' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2, K2Node_ComponentBoundEvent_Sender_1) == 0x000010, "Member 'UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2::K2Node_ComponentBoundEvent_Sender_1' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2, K2Node_ComponentBoundEvent_Sender) == 0x000018, "Member 'UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2::K2Node_ComponentBoundEvent_Sender' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2, CallFunc_GetOwningPlayer_ReturnValue) == 0x000020, "Member 'UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000028, "Member 'UI_WeaponGridSlot_2_C_ExecuteUbergraph_UI_WeaponGridSlot_2::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");

// Function UI_WeaponGridSlot_2.UI_WeaponGridSlot_2_C.BndEvt__UI_WeaponGridSlot_2_InteractButton-ForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature final
{
public:
	class UButton*                                Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");
static_assert(sizeof(UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature) == 0x000008, "Wrong size on UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");
static_assert(offsetof(UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature, Sender) == 0x000000, "Member 'UI_WeaponGridSlot_2_C_BndEvt__UI_WeaponGridSlot_2_InteractButtonMinusForcharityboxonlyMustnotbehittablealways_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature::Sender' has a wrong offset!");

// Function UI_WeaponGridSlot_2.UI_WeaponGridSlot_2_C.BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature final
{
public:
	class UButton*                                Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature");
static_assert(sizeof(UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature) == 0x000008, "Wrong size on UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature");
static_assert(offsetof(UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature, Sender) == 0x000000, "Member 'UI_WeaponGridSlot_2_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature::Sender' has a wrong offset!");

// Function UI_WeaponGridSlot_2.UI_WeaponGridSlot_2_C.BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature final
{
public:
	class UButton*                                Sender;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature");
static_assert(sizeof(UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature) == 0x000008, "Wrong size on UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature");
static_assert(offsetof(UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature, Sender) == 0x000000, "Member 'UI_WeaponGridSlot_2_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature::Sender' has a wrong offset!");

// Function UI_WeaponGridSlot_2.UI_WeaponGridSlot_2_C.UpdateItemCount
// 0x0018 (0x0018 - 0x0000)
struct UI_WeaponGridSlot_2_C_UpdateItemCount final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AItem*                                  CallFunc_GetItemObsolete_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_WeaponGridSlot_2_C_UpdateItemCount) == 0x000008, "Wrong alignment on UI_WeaponGridSlot_2_C_UpdateItemCount");
static_assert(sizeof(UI_WeaponGridSlot_2_C_UpdateItemCount) == 0x000018, "Wrong size on UI_WeaponGridSlot_2_C_UpdateItemCount");
static_assert(offsetof(UI_WeaponGridSlot_2_C_UpdateItemCount, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'UI_WeaponGridSlot_2_C_UpdateItemCount::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_UpdateItemCount, CallFunc_GetItemObsolete_ReturnValue) == 0x000008, "Member 'UI_WeaponGridSlot_2_C_UpdateItemCount::CallFunc_GetItemObsolete_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_WeaponGridSlot_2_C_UpdateItemCount, CallFunc_IsValid_ReturnValue_1) == 0x000010, "Member 'UI_WeaponGridSlot_2_C_UpdateItemCount::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function UI_WeaponGridSlot_2.UI_WeaponGridSlot_2_C.SetCharityButtonVisibility
// 0x0001 (0x0001 - 0x0000)
struct UI_WeaponGridSlot_2_C_SetCharityButtonVisibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_WeaponGridSlot_2_C_SetCharityButtonVisibility) == 0x000001, "Wrong alignment on UI_WeaponGridSlot_2_C_SetCharityButtonVisibility");
static_assert(sizeof(UI_WeaponGridSlot_2_C_SetCharityButtonVisibility) == 0x000001, "Wrong size on UI_WeaponGridSlot_2_C_SetCharityButtonVisibility");
static_assert(offsetof(UI_WeaponGridSlot_2_C_SetCharityButtonVisibility, Visibility_0) == 0x000000, "Member 'UI_WeaponGridSlot_2_C_SetCharityButtonVisibility::Visibility_0' has a wrong offset!");

}

