#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Waterfall_collide_top

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Waterfall_collide_top.Waterfall_collide_top
// NumValues: 0x0004
enum class EWaterfall_collide_top : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator5                           = 2,
	Waterfall_collide_MAX                    = 3,
};

}

